#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.8"
# dependencies = ["pyyaml"]
# ///
"""
AgentWire Bash Tool Damage Control
==================================

Claude Code PreToolUse hook for Bash tool calls. Decides allow/block/ask based
on the merged rule set under ``agentwire/hooks/damage-control/rules/*.yaml``
(or the user's ``~/.agentwire/damage-control/*.yaml`` override) plus
ask-patterns generated from write-tier tooldef commands.

Implementation: the body of ``agentwire/safety/_core.py`` is inlined below
between the BEGIN/END GENERATED markers. Edit ``_core.py``, then run
``scripts/regen_damage_control_hooks.py`` — never edit between the markers.
"""

import json
import os
import sys
from pathlib import Path

# audit_logger lives next to this script
try:
    from audit_logger import log_allowed, log_asked, log_blocked, log_disabled, log_escape
except ImportError:
    def log_allowed(*args, **kwargs): pass
    def log_asked(*args, **kwargs): pass
    def log_blocked(*args, **kwargs): pass
    def log_disabled(*args, **kwargs): pass
    def log_escape(*args, **kwargs): pass


# === BEGIN GENERATED FROM agentwire/safety/_core.py ===
"""
Shared damage-control logic for both the agentwire CLI (`agentwire safety check`)
and the Claude Code PreToolUse hooks (bash/edit/write).

Single source of truth. The hook scripts inline this file's contents at the time
they're regenerated by ``scripts/regen_damage_control_hooks.py``; do not let this
file drift from what's inlined. ``tests/unit/test_damage_control_sync.py`` will
fail loudly if drift happens.
"""

import fnmatch
import json
import os
import re
import shlex
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

try:
    import yaml
except ImportError:
    yaml = None


# ============================================================================
# CONSTANTS
# ============================================================================

ALL_OPERATIONS = {"read", "write", "edit", "delete", "move", "chmod"}

# Operation pattern tuples: (regex template with {path} placeholder, operation name).

WRITE_PATTERNS = [
    (r'>\s*{path}', "write"),
    (r'\btee\s+(?!.*-a).*{path}', "write"),
    (r'\bdd\s+.*\bof=\S*{path}', "write"),
    (r'\brsync\s+.*\s+{path}', "write"),
    (r'\btar\s+(-c|--create)\S*\s+.*{path}', "write"),
    (r'\binstall\s+.*\s+{path}', "write"),
]

APPEND_PATTERNS = [
    (r'>>\s*{path}', "append"),
    (r'\btee\s+-a\s+.*{path}', "append"),
    (r'\btee\s+.*-a.*{path}', "append"),
]

EDIT_PATTERNS = [
    (r'\bsed\s+-i.*{path}', "edit"),
    (r'\bperl\s+-[^\s]*i.*{path}', "edit"),
    (r'\bawk\s+-i\s+inplace.*{path}', "edit"),
]

MOVE_COPY_PATTERNS = [
    (r'\bmv\s+.*\s+{path}', "move"),
    (r'\bcp\s+.*\s+{path}', "copy"),
]

DELETE_PATTERNS = [
    (r'\brm\s+.*{path}', "delete"),
    (r'\bunlink\s+.*{path}', "delete"),
    (r'\brmdir\s+.*{path}', "delete"),
    (r'\bshred\s+.*{path}', "delete"),
]

PERMISSION_PATTERNS = [
    (r'\bchmod\s+.*{path}', "chmod"),
    (r'\bchown\s+.*{path}', "chown"),
    (r'\bchgrp\s+.*{path}', "chgrp"),
]

TRUNCATE_PATTERNS = [
    (r'\btruncate\s+.*{path}', "truncate"),
    (r':\s*>\s*{path}', "truncate"),
]

READ_ONLY_BLOCKED = (
    WRITE_PATTERNS
    + APPEND_PATTERNS
    + EDIT_PATTERNS
    + MOVE_COPY_PATTERNS
    + DELETE_PATTERNS
    + PERMISSION_PATTERNS
    + TRUNCATE_PATTERNS
)

NO_DELETE_BLOCKED = DELETE_PATTERNS

# Interpreter programs can write a file without any shell-level write token:
# ``python3 -c 'open(p, "w")...'``, a heredoc piped into ``python -``, or
# ``echo 'open(p,"w")' | python3``. The program text is opaque to static
# matching, so for PROTECTED control-plane paths we fail closed: an interpreter
# invocation that takes inline code (-c/-e, combined forms like ``perl -pie``),
# a heredoc/stdin program, or has data piped into it, AND mentions a protected
# path anywhere in the command, is blocked (#678). Applied ONLY by
# ``check_protected_command`` — never to user readOnlyPaths rules — so a
# legitimate read via ``cat``/``grep`` stays allowed.
_INTERPRETERS = r'(?:python[\d.]*|perl|ruby|node|deno|bun|php)'
INTERPRETER_WRITE_PATTERNS = [
    # interpreter ... -c/-e/... or stdin/heredoc marker, path anywhere after
    (r'\b' + _INTERPRETERS +
     r'\b[^\n|;&]*(?:\s-\S*[ceE]\b|\s+-\s|\s+-$|<<)(?s:.*){path}',
     "interpreter program"),
    # path anywhere before a pipe into an interpreter
    (r'{path}(?s:.*)\|\s*' + _INTERPRETERS + r'\b', "pipe into interpreter"),
]


# ============================================================================
# GLOB / PATH HELPERS
# ============================================================================


def is_glob_pattern(pattern: str) -> bool:
    return '*' in pattern or '?' in pattern or '[' in pattern


def glob_to_regex(pattern: str) -> str:
    """Convert a glob to a regex usable inside command-line contexts.

    Trailing word-boundary check ensures e.g. ``*.py`` doesn't match
    ``foo.python``.
    """
    result = ""
    for char in pattern:
        if char == '*':
            result += r'[^\s/]*'
        elif char == '?':
            result += r'[^\s/]'
        elif char in r'\.^$+{}[]|()':
            result += '\\' + char
        else:
            result += char
    result += r'(?![a-zA-Z0-9_])'
    return result


def canonicalize_command(command: str) -> str:
    """Expand ``~``, ``$HOME`` and ``${HOME}`` in a command to the home dir.

    The rule patterns are stored in ``~``-form and expanded with
    ``expanduser`` before matching; without expanding the COMMAND too, a
    tilde/``$HOME`` secret read (``cat ~/.ssh/id_rsa``, ``cat $HOME/.aws/credentials``)
    only ever matched against its fully-expanded ``/Users/<me>/...`` form and
    slipped past. Canonicalizing both sides closes that gap. ``./``-prefixes are
    handled by the path-context boundary in :func:`path_match_regex` (a leading
    ``/`` is an accepted boundary char), so no separate ``normpath`` of the raw
    command string — which is not a pure path — is attempted here.
    """
    home = os.path.expanduser("~")
    if not home or home == "~":
        return command
    out = command.replace("${HOME}", home).replace("$HOME", home)
    # Only expand ``~`` when it begins a path (start of string or after a
    # whitespace/quote/=/: boundary and immediately followed by ``/``), so we
    # never touch ``~`` used as a literal (e.g. inside a sed expression).
    out = re.sub(r'(^|[\s=:"\'(<>])~(?=/)', lambda m: m.group(1) + home, out)
    return out


def path_match_regex(expanded_pattern: str) -> str:
    """Build a path-context regex for a rule pattern (glob or literal).

    Both glob and literal patterns are matched as a whole path COMPONENT — never
    a bare substring. The literal branch previously used ``expanded in command``,
    which hard-blocked innocuous text: ``.env`` matched ``.environment``,
    ``docs/.env.example``, ``grep -v .environ`` (#492). The component boundary
    (a leading path-separator/whitespace boundary, and a trailing boundary that
    forbids the basename being extended by another filename char) fixes those
    false positives while still catching real secret paths.
    """
    lead = r'(?:^|[\s=:"\'<>(/])'
    if is_glob_pattern(expanded_pattern):
        glob_regex = glob_to_regex(expanded_pattern)
        return r'(?:^|[\s/="\'<>])' + glob_regex + r'(?:[\s"\')<>]|$)'
    is_dir = expanded_pattern.endswith('/')
    body = re.escape(expanded_pattern.rstrip('/'))
    if is_dir:
        # Directory prefix: anything under it counts as a hit.
        trail = r'(?:/|[\s"\')<>;&|]|$)'
    else:
        # Filename/path: the basename must end here — the next char must not be
        # a path-extending char, so ``.env`` no longer matches ``.env.example``.
        trail = r'(?![A-Za-z0-9_.\-])'
    return lead + body + trail


# ``.env.example`` / ``.env.sample`` / ``.env.template`` / ``.env.dist`` are
# committed, secret-free TEMPLATE files — never the real env. The ``.env.*`` glob
# would otherwise hard-block reading them (#492), so they are carved out.
_SAFE_ENV_TEMPLATE_RE = re.compile(
    r'\.env\.(?:example|sample|template|dist)(?![A-Za-z0-9_])', re.IGNORECASE
)


def matches_path_in_command(pattern: str, command: str) -> bool:
    """Check if a path pattern occurs in a command string in a path-context.

    The command is canonicalized (``~``/``$HOME`` expanded) and the pattern is
    matched as a whole path component against both the raw and canonicalized
    forms, so neither tilde indirection (#2) nor bare-substring over-blocking
    (#492) defeats it.
    """
    expanded = os.path.expanduser(pattern)
    regex = path_match_regex(expanded)
    haystacks = [command]
    canon = canonicalize_command(command)
    if canon != command:
        haystacks.append(canon)

    matched = False
    for hay in haystacks:
        try:
            m = re.search(regex, hay, re.IGNORECASE)
        except re.error:
            return False
        if m and not _SAFE_ENV_TEMPLATE_RE.search(m.group(0)):
            matched = True
            break
    if not matched:
        return False

    if is_glob_pattern(pattern):
        # Reject method-call lookalikes: foo.py( should not match *.py
        extension = pattern.split('*')[-1] if '*' in pattern else pattern
        if extension.startswith('.'):
            extension = extension[1:]
        if extension and re.search(r'\w\.' + re.escape(extension) + r'\s*\(', command):
            return False
    return True


def match_path(file_path: str, pattern: str) -> bool:
    """Match a single absolute file path against a pattern (glob or prefix)."""
    expanded_pattern = os.path.expanduser(pattern)
    normalized = os.path.normpath(file_path)
    expanded_normalized = os.path.expanduser(normalized)
    if is_glob_pattern(pattern):
        lower_path = expanded_normalized.lower()
        lower_pattern = expanded_pattern.lower()
        if fnmatch.fnmatch(lower_path, lower_pattern):
            return True
        basename = os.path.basename(expanded_normalized)
        if fnmatch.fnmatch(basename.lower(), lower_pattern):
            return True
        return False
    return (
        expanded_normalized.startswith(expanded_pattern)
        or expanded_normalized == expanded_pattern.rstrip('/')
    )


def _parse_allowed_entry(entry: Dict[str, Any]) -> Dict[str, Any]:
    """Normalize an allowed-paths entry to ``{path: str, allow: set}``."""
    allow = entry.get("allow", "all")
    if isinstance(allow, str) and allow.strip().lower() == "all":
        return {"path": entry["path"], "allow": ALL_OPERATIONS.copy()}
    if isinstance(allow, list):
        return {"path": entry["path"], "allow": {a.strip().lower() for a in allow}}
    if isinstance(allow, str):
        return {"path": entry["path"], "allow": {allow.strip().lower()}}
    return {"path": entry["path"], "allow": ALL_OPERATIONS.copy()}


def _find_project_config() -> Tuple[str, List[Any]]:
    """Walk up from $PWD to find ``.damagecontrol.yml`` and return its allowed_paths.

    The per-project allowlist lives in the PROTECTED ``.damagecontrol.yml``
    (top-level ``allowed_paths``), never the agent-writable ``.agentwire.yml``.
    Otherwise an agent could allowlist a control-plane path in ``.agentwire.yml``
    and re-permit its own write to ``damagecontrol.yml`` — the exact bypass #466
    set out to close. The allowlist is the one knob that overrides the protected
    check, so it must itself live behind the protected control plane (#467).
    """
    cwd = os.environ.get("PWD", os.getcwd())
    current = os.path.abspath(cwd)
    while True:
        config_file = os.path.join(current, ".damagecontrol.yml")
        if os.path.isfile(config_file):
            try:
                if yaml:
                    with open(config_file, "r") as f:
                        data = yaml.safe_load(f) or {}
                    if isinstance(data, dict):
                        paths = data.get("allowed_paths", [])
                        if isinstance(paths, list):
                            return current, paths
            except Exception:
                pass
            return current, []
        parent = os.path.dirname(current)
        if parent == current:
            break
        current = parent
    return cwd, []


def load_allowed_paths(config: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Merge global ``allowedPaths`` from config with per-project ``.damagecontrol.yml`` entries."""
    raw = list(config.get("allowedPaths", []))

    project_root, project_paths = _find_project_config()
    for p in project_paths:
        if not isinstance(p, dict):
            continue
        entry = _parse_allowed_entry(p)
        if not os.path.isabs(os.path.expanduser(entry["path"])):
            entry["path"] = os.path.join(project_root, entry["path"])
        raw.append(entry)

    result = []
    for item in raw:
        if not isinstance(item, dict):
            continue
        if "allow" in item and isinstance(item["allow"], set):
            result.append(item)
        else:
            result.append(_parse_allowed_entry(item))
    return result


def is_path_allowed_for_op(
    file_path: str,
    allowed_paths: List[Dict[str, Any]],
    operation: str,
) -> bool:
    """Check if ``file_path`` has ``operation`` permitted by some allowed-path entry."""
    for entry in allowed_paths:
        if match_path(file_path, entry["path"]):
            if operation in entry["allow"]:
                return True
    return False


def _extract_command_paths(command: str) -> List[str]:
    """Extract file/directory paths from a bash command string."""
    paths = []
    for m in re.finditer(r'''["']([^"']+)["']''', command):
        candidate = m.group(1)
        if '/' in candidate or candidate.startswith('.'):
            paths.append(os.path.expanduser(candidate))
    for token in re.split(r'\s+', command):
        token = token.strip("\"'")
        if token.startswith(('/', '~/', './')):
            paths.append(os.path.expanduser(token))
        elif '/' in token and not token.startswith('-'):
            paths.append(os.path.expanduser(token))
    return paths


def is_command_path_allowed(
    command: str,
    allowed_paths: List[Dict[str, Any]],
    operation: str = "write",
) -> bool:
    """ALL paths in ``command`` must have ``operation`` permitted by allowlist.

    Security: ALL paths must match (not any) — this stops e.g.
    ``rm /tmp/safe.txt /etc/passwd`` from being allowed just because /tmp is
    allowlisted.
    """
    if not allowed_paths:
        return False
    paths = _extract_command_paths(command)
    if not paths:
        return False
    for p in paths:
        if not is_path_allowed_for_op(p, allowed_paths, operation):
            return False
    return True


def _infer_operation_from_reason(reason: str) -> str:
    """Map a pattern's reason text back to one of the allowlist operation names."""
    reason_lower = reason.lower()
    if (
        "rm" in reason_lower
        or "delet" in reason_lower
        or "trash" in reason_lower
        or "rmdir" in reason_lower
    ):
        return "delete"
    if "chmod" in reason_lower or "permission" in reason_lower:
        return "chmod"
    if "chown" in reason_lower or "chgrp" in reason_lower:
        return "chmod"
    if "mv" in reason_lower or "move" in reason_lower:
        return "move"
    return "write"


def check_path_patterns(
    command: str,
    path: str,
    patterns: List[Tuple[str, str]],
    path_type: str,
) -> Tuple[bool, str]:
    """Check if any operation pattern matches ``command`` targeting ``path``.

    Returns ``(matched, reason)`` where reason names the operation that triggered.
    """
    if is_glob_pattern(path):
        # Allow an optional (possibly quoted) directory prefix: ``*`` in the
        # glob can't span ``/``, so without this a basename glob like
        # ``*.agentwire.yml`` never matched an absolute target
        # (``> /repo/.agentwire.yml`` sailed past every write pattern) (#678).
        path_regex = r'["\']?(?:[^\s"\';|&<>]*/)?' + glob_to_regex(path)
    else:
        expanded = os.path.expanduser(path)
        if expanded == path:
            path_regex = re.escape(path)
        else:
            path_regex = r'(?:' + re.escape(expanded) + r'|' + re.escape(path) + r')'

    for pattern_template, operation in patterns:
        try:
            full_pattern = pattern_template.replace("{path}", path_regex)
            if re.search(full_pattern, command, re.IGNORECASE):
                return True, f"{operation} operation on {path_type} {path}"
        except re.error:
            continue
    return False, ""


# ============================================================================
# CONFIG LOADING
# ============================================================================


def _cmd_to_regex(cmd: str) -> Optional[str]:
    """Convert a tooldef command string to a regex matching its fixed prefix.

    Stops at the first flag (- or --), placeholder (<...>), or optional ([...]).
    Example: ``gws gmail +send --to <addr>`` -> ``\\bgws\\s+gmail\\s+\\+send\\b``
    """
    tokens = cmd.strip().split()
    fixed = []
    for token in tokens:
        if token.startswith('<') or token.startswith('[') or token.startswith('-'):
            break
        fixed.append(token)
    if not fixed:
        return None
    parts = [re.escape(t) for t in fixed]
    pattern = r'\b' + r'\s+'.join(parts)
    last = fixed[-1]
    if last and (last[-1].isalnum() or last[-1] == '_'):
        pattern += r'\b'
    return pattern


def load_write_patterns_from_tooldefs(tooldefs_dir: Optional[Path]) -> List[Dict[str, Any]]:
    """Generate ``ask:true`` patterns from write-tier commands in tooldef YAMLs."""
    if not yaml:
        return []
    patterns: List[Dict[str, Any]] = []
    if not tooldefs_dir or not tooldefs_dir.exists():
        return patterns
    for tf_file in sorted(tooldefs_dir.glob("*.yaml")):
        try:
            with open(tf_file, "r") as f:
                data = yaml.safe_load(f) or {}
            tool_name = data.get("name", tf_file.stem)
            for cmd_def in data.get("commands", []):
                if cmd_def.get("access") != "write":
                    continue
                cmd_str = cmd_def.get("cmd", "")
                regex = _cmd_to_regex(cmd_str)
                if not regex:
                    continue
                entry = {
                    "pattern": regex,
                    "reason": f"{tool_name}: {cmd_def.get('description', cmd_str)}",
                    "ask": True,
                    # Command-prefix rule: match command position only, never
                    # quoted argument/message content (#675).
                    "anchored": True,
                }
                # An explicit ``id:`` on the tooldef command yields a stable
                # rule ID (e.g. ``git.push``) that survives description edits —
                # needed so ``safety.unattended_allow`` can name it reliably.
                # Without one, ``_assign_rule_id`` derives a slug from the reason.
                if cmd_def.get("id"):
                    entry["id"] = str(cmd_def["id"])
                patterns.append(entry)
        except Exception:
            continue
    return patterns


_RULE_ID_SLUG_RE = re.compile(r"[^a-z0-9]+")


def _slug_for_rule(text: str, max_len: int = 60) -> str:
    """Lowercase, ASCII, kebab-case slug suitable for rule IDs."""
    s = _RULE_ID_SLUG_RE.sub("-", (text or "").lower()).strip("-")
    return s[:max_len] or "rule"


def _assign_rule_id(pattern_obj: Dict[str, Any], file_stem: str, taken: set) -> str:
    """Generate (or honor) an ID for a bash pattern. Mutates pattern_obj in place."""
    existing = pattern_obj.get("id")
    if isinstance(existing, str) and existing.strip():
        pattern_obj["id"] = existing.strip()
        taken.add(pattern_obj["id"])
        return pattern_obj["id"]
    slug = _slug_for_rule(pattern_obj.get("reason", "rule"))
    candidate = f"{file_stem}.{slug}"
    n = 2
    while candidate in taken:
        candidate = f"{file_stem}.{slug}-{n}"
        n += 1
    pattern_obj["id"] = candidate
    taken.add(candidate)
    return candidate


def load_config(
    rules_dir: Path,
    tooldefs_dir: Optional[Path] = None,
) -> Dict[str, Any]:
    """Load and merge all rule YAMLs in ``rules_dir`` plus tooldef ask-patterns.

    Bash patterns get a stable ``id`` field (``"<file>.<slug-of-reason>"``) so
    they can be referenced by the ``safety.disabled_rules`` config.
    """
    merged: Dict[str, Any] = {
        "bashToolPatterns": [],
        "zeroAccessPaths": [],
        "readOnlyPaths": [],
        "noDeletePaths": [],
        "allowedPaths": [],
    }
    if not yaml:
        # No YAML parser ⇒ we cannot load ANY rules. Returning the empty rule set
        # would silently disable all protection (fail OPEN). Mark the config so
        # the decision ladder fails CLOSED instead.
        merged["_parser_unavailable"] = "pyyaml unavailable — cannot load rules"
        return merged
    if not rules_dir.exists():
        return merged
    taken_ids: set = set()
    yaml_files = sorted(rules_dir.glob("*.yaml"))
    for rules_file in yaml_files:
        try:
            with open(rules_file, "r") as f:
                data = yaml.safe_load(f) or {}
            for key in merged:
                items = data.get(key, []) or []
                if key == "bashToolPatterns":
                    for it in items:
                        if isinstance(it, dict):
                            _assign_rule_id(it, rules_file.stem, taken_ids)
                            it.setdefault("source", rules_file.stem)
                merged[key].extend(items)
        except Exception:
            continue
    if tooldefs_dir is not None:
        tooldef_patterns = load_write_patterns_from_tooldefs(tooldefs_dir)
        for it in tooldef_patterns:
            _assign_rule_id(it, "tooldef", taken_ids)
            it.setdefault("source", "tooldef")
        merged["bashToolPatterns"].extend(tooldef_patterns)
    return merged


# ============================================================================
# UNATTENDED (NO-HUMAN-PRESENT) RESOLUTION
# ============================================================================
#
# The damage-control hook classifies commands into allow / block / ask. The
# ``ask`` tier only means something when a human is present to confirm. Under
# the scheduler (cron, nobody watching) sessions run with
# ``--dangerously-skip-permissions``, so historically ``ask`` resolved to a
# SILENT allow — an unsupervised agent could deploy / drop a table / force-push.
#
# When a session is marked unattended (``AGENTWIRE_UNATTENDED=1``, stamped at
# dispatch by the scheduler), the hook resolves ``ask`` by FAILING CLOSED:
# block + notify the owner, UNLESS the matched rule's stable ID carries a GRANT.
# Grants come from three sources, most specific first:
#   1. ``AGENTWIRE_UNATTENDED_ALLOW`` — the per-task extension the scheduler
#      stamps from a task's ``unattended_allow``,
#   2. ``safety.unattended_allow`` from the host-owned damage-control files,
#   3. ``DEFAULT_UNATTENDED_ALLOW`` below (work + open a PR + notify the owner
#      by email — nothing else irreversible or outward-facing).
#
# PRECEDENCE, NOT UNION (#914): the most specific source that NAMES a rule id
# defines that rule's grant outright. A union would make the whole point of a
# scoped entry unexpressible — ``git.commit`` is already granted unscoped by the
# default set, so a task writing ``{id: git.commit, paths: [<store>]}`` under a
# union would read as a constraint and be silently meaningless. That class of
# config-that-lies is exactly what this issue is about, so naming a rule at a
# more specific level REPLACES the looser grant for that dispatch. Within one
# source, several entries for the same id union their scopes.
#
# SCOPES (#914). A grant entry is either a bare rule id (unscoped — the rule is
# permitted wherever it fires) or a mapping carrying ``paths``:
#
#     unattended_allow:
#       - outbound.agentwire-email                  # bare: unchanged, still works
#       - id: tooldef.git-create-a-commit
#         paths:
#           - ~/.claude/projects/*/memory/          # scoped: only under here
#
# A scoped grant applies only when EVERY directory the matching command would
# act on resolves inside one of ``paths``. Anything that makes the target
# directory unknowable — a ``cd``, an indirect runner (``sh -c``, ``xargs``,
# ``sudo``, ``ssh`` …), command substitution — does NOT apply the grant, so the
# unattended block fires exactly as it did before the grant existed. Scope
# evaluation can only ever REFUSE a command the bare form would have allowed;
# it can never permit one.
#
# Hard ``block`` rules (rm -rf, git push --force, …) are unaffected — they fire
# regardless. Interactive bypass sessions (no ``AGENTWIRE_UNATTENDED``) are
# unaffected too — their ``ask`` still resolves the old way.

# The built-in grants. Written in the SAME shape as a task's
# ``unattended_allow`` (bare id = unscoped, or ``{id, paths}`` = scoped) and
# parsed by the same parser, so a scope is expressible HERE too — not only in a
# per-task entry (#914 review §2). That matters because these ids are the
# widest grants in the system: ``git.commit`` / ``git.push`` unscoped means any
# repo on the machine, in every scheduled task, forever.
#
# They are deliberately left UNSCOPED here — narrowing them is a host policy
# decision, not something this file should make on every install's behalf, and
# a task that needs a narrower grant can already express it: naming a rule at a
# more specific level REPLACES this one (see the precedence note above), so a
# task's ``{id: git.commit, paths: [<store>]}`` genuinely binds rather than
# being swallowed by this unscoped default. A host that wants the narrow form
# machine-wide writes the scoped entry in ``~/.agentwire/damagecontrol.yml``.
#
# NOTE (#916 / review §2): these ids only exist if the LOADED tooldefs carry
# them. ``~/.agentwire/tooldefs/`` wins over the bundled copy and never
# self-heals, so on a drifted install five of the six name no rule at all and
# every one of these actions is blocked unattended. ``agentwire doctor`` now
# reports that (``_check_unattended_defaults``) instead of leaving it to be
# rediscovered as a nightly timeout.
DEFAULT_UNATTENDED_ALLOW = [
    "git.add",       # stage files
    "git.add-u",     # stage tracked changes
    "git.commit",    # commit
    "git.push",      # push (force/delete are SEPARATE hard-block/ask rules)
    "gh.pr-create",  # open a PR — the human-reviewed gate
    "outbound.agentwire-email",  # blanket allow, any recipient (#804)
]


def is_unattended() -> bool:
    """True when this session was dispatched with no human present (scheduler)."""
    return os.environ.get("AGENTWIRE_UNATTENDED") == "1"


# ---------------------------------------------------------------------------
# Grant parsing
# ---------------------------------------------------------------------------


def parse_unattended_allow(raw: Any) -> Tuple[Dict[str, List[List[str]]], List[str]]:
    """Parse one ``unattended_allow`` list into ``({id: [scope, ...]}, errors)``.

    A ``scope`` is a list of absolute path patterns; the EMPTY list means
    unscoped. So ``{"git.commit": [[]]}`` grants commits anywhere, while
    ``{"git.commit": [["~/x/"]]}`` grants them only under ``~/x/``.

    ``errors`` describes entries that were REFUSED (and therefore grant
    nothing) — malformed shapes, missing ids, relative path patterns. Callers
    that lint surface them; the hook simply gets a grant map without them,
    which is the fail-closed direction: an entry the host thought they wrote
    cannot silently become a broader grant than they typed.
    """
    grants: Dict[str, List[List[str]]] = {}
    errors: List[str] = []
    if raw is None:
        return grants, errors
    if not isinstance(raw, (list, tuple)):
        return grants, [f"unattended_allow must be a list, got {type(raw).__name__}"]

    for entry in raw:
        if isinstance(entry, str):
            rid = entry.strip()
            if rid:
                grants.setdefault(rid, []).append([])
            continue
        if not isinstance(entry, dict):
            errors.append(f"entry must be a rule id or a mapping, got {entry!r}")
            continue
        rid = str(entry.get("id", "")).strip()
        if not rid:
            errors.append(f"entry {entry!r} has no `id`")
            continue
        unknown = sorted(set(entry) - {"id", "paths"})
        if unknown:
            # Same reasoning as TaskConfig.unknown_keys (#867): a key we ignore
            # is a constraint the author believes they set.
            errors.append(f"{rid}: ignored key(s) {', '.join(unknown)}")
        raw_paths = entry.get("paths")
        if raw_paths is None:
            grants.setdefault(rid, []).append([])
            continue
        if not isinstance(raw_paths, (list, tuple)):
            errors.append(f"{rid}: `paths` must be a list")
            continue
        scope: List[str] = []
        bad = False
        for p in raw_paths:
            p = str(p).strip()
            if not p:
                continue
            if not (p.startswith("/") or p.startswith("~")):
                # A relative scope has no fixed meaning — it would silently
                # change with the dispatch cwd, which is the one thing a scope
                # exists to pin down. Refuse the whole entry.
                errors.append(f"{rid}: scope path must be absolute or ~-rooted, got {p!r}")
                bad = True
                continue
            scope.append(p)
        if bad:
            continue
        if not scope:
            errors.append(f"{rid}: `paths` is empty — write a bare rule id for an unscoped grant")
            continue
        grants.setdefault(rid, []).append(scope)
    return grants, errors


def _env_unattended_allow() -> Any:
    """Decode ``AGENTWIRE_UNATTENDED_ALLOW`` into an ``unattended_allow`` list.

    Two wire forms, discriminated unambiguously (a rule id can never start with
    ``[``): a JSON array when any entry is scoped, else the plain
    comma-separated id list — which stays readable in ``tmux show-environment``
    for the common case. ``scheduler/dispatch.py::_unattended_env`` is the only
    writer; see ``encode_unattended_allow``.
    """
    raw = os.environ.get("AGENTWIRE_UNATTENDED_ALLOW", "")
    if not raw.strip():
        return []
    if raw.lstrip().startswith("["):
        try:
            decoded = json.loads(raw)
        except ValueError:
            # Undecodable ⇒ grant NOTHING rather than fall back to a comma
            # split that would read `{"id": "x"` as a rule id.
            return []
        return decoded if isinstance(decoded, list) else []
    return [part.strip() for part in raw.split(",") if part.strip()]


def encode_unattended_allow(entries: Any) -> str:
    """Encode an ``unattended_allow`` list for ``AGENTWIRE_UNATTENDED_ALLOW``."""
    items = list(entries or [])
    if any(not isinstance(e, str) for e in items):
        return json.dumps(items, separators=(",", ":"))
    return ",".join(e.strip() for e in items if e and e.strip())


def resolve_unattended_grants(config: Dict[str, Any]) -> Dict[str, List[List[str]]]:
    """Effective unattended grants: ``{rule id: [scope, ...]}``.

    Precedence, most specific wins outright (see the section header): per-task
    env > host config > ``DEFAULT_UNATTENDED_ALLOW``.
    """
    safety_cfg = config.get("safety", {}) if isinstance(config.get("safety"), dict) else {}
    layers = [
        parse_unattended_allow(_env_unattended_allow())[0],
        parse_unattended_allow(safety_cfg.get("unattended_allow"))[0],
        parse_unattended_allow(DEFAULT_UNATTENDED_ALLOW)[0],
    ]
    merged: Dict[str, List[List[str]]] = {}
    for layer in layers:
        for rid, scopes in layer.items():
            if rid not in merged:
                merged[rid] = scopes
    return merged


# ---------------------------------------------------------------------------
# Scope evaluation — which directories would this command act on?
# ---------------------------------------------------------------------------

# Builtins that move the working directory. Their effect on a LATER subcommand
# is not statically knowable, so their presence makes the whole command
# unscopeable.
_CWD_CHANGING = {"cd", "pushd", "popd", "chdir"}

# Programs whose job is to run ANOTHER program. The rule matched text inside
# them, so the directory the real work happens in is whatever the inner command
# decides — not something this parser can claim to know.
_INDIRECT_RUNNERS = {
    "sh", "bash", "zsh", "dash", "ksh", "fish",
    "env", "xargs", "sudo", "doas", "su", "ssh", "nohup", "setsid",
    "timeout", "nice", "ionice", "stdbuf", "script", "watch", "parallel",
    "command", "exec", "time", "find", "make", "nix-shell", "docker", "podman",
}

# git's directory-redirecting global options. `-C` and `--git-dir` /
# `--work-tree` all accept BOTH `--opt=<path>` and `--opt <path>` against the
# real binary (verified on git 2.50.1 in #913's review), so both are parsed.
#
# COORDINATION WITH #913: that issue normalizes git's global options out of the
# command BEFORE rule matching, so every git rule stops being defeated by
# `git -C <dir> …`. This function is the shared parser for that grammar —
# #913's normalizer should consume `git_global_dirs` rather than write a second
# copy, and the two have opposite needs on the same data: the normalizer wants
# the options GONE, scope evaluation wants the directory they name. Splitting
# it here gives both from one implementation.
_GIT_DIR_OPTS_VALUE = {"-C", "--git-dir", "--work-tree"}


def git_global_dirs(argv: List[str]) -> Tuple[List[str], List[str]]:
    """Split a ``git`` argv into ``(directories it redirects to, remaining argv)``.

    ``remaining argv`` is the command with git's global options removed —
    ``["git", "commit", "-m", "x"]`` for ``git -C /r commit -m x`` — which is
    the form a rule pattern like ``\\bgit\\s+commit\\b`` was written against.
    """
    dirs: List[str] = []
    rest: List[str] = argv[:1]
    i = 1
    while i < len(argv):
        tok = argv[i]
        if tok in _GIT_DIR_OPTS_VALUE:
            if i + 1 < len(argv):
                dirs.append(argv[i + 1])
            i += 2
            continue
        matched = False
        for opt in _GIT_DIR_OPTS_VALUE:
            if tok.startswith(opt + "="):
                dirs.append(tok[len(opt) + 1:])
                matched = True
                break
        if matched:
            i += 1
            continue
        if tok == "-c" or tok == "--config-env":
            # Takes a value, names no directory. Consume both so the value
            # can't be mistaken for the subcommand.
            i += 2
            continue
        if tok.startswith("-"):
            i += 1
            continue
        rest.extend(argv[i:])
        break
    return dirs, rest


def _strip_assignments(argv: List[str]) -> List[str]:
    """Drop leading ``VAR=value`` prefixes (``FOO=1 git commit`` -> ``git commit``)."""
    i = 0
    while i < len(argv) and _ASSIGN_TOKEN_RE.match(argv[i]):
        i += 1
    return argv[i:]


# Shell operators, and the grouping tokens that make a segment's execution
# context something this parser will not reason about.
_SCOPE_OPERATORS = {";", "&&", "||", "|", "&", "\n", ";;", "|&"}
_SCOPE_GROUPING = {"(", ")", "{", "}"}


def _scope_segments(command: str) -> Tuple[List[Tuple[List[str], str]], Optional[str]]:
    """Split ``command`` into ``[(argv, operator_that_follows)]``.

    This is a SECOND, deliberately separate splitter from
    ``normalize_subcommands`` — that one discards the operators, and scope
    evaluation needs them: ``cd X && git commit`` and ``cd X ; git commit``
    describe different directories for the same ``git commit``.

    OWNERSHIP NOTE (#913/#914/#915 orchestrator ruling): ``normalize_subcommands``
    / ``masked_subcommands`` / the haystack selection belong to #913, and this
    file must not fork them. So scope evaluation gets its own local splitter
    rather than an edit there. Once #913 has landed its haystack work, these two
    are a consolidation candidate — flagged, not done here.
    """
    try:
        lex = shlex.shlex(command, posix=True, punctuation_chars=True)
        lex.whitespace_split = True
        tokens = list(lex)
    except ValueError:
        return [], "unbalanced quotes"

    segments: List[Tuple[List[str], str]] = []
    cur: List[str] = []
    for tok in tokens:
        if tok in _SCOPE_GROUPING:
            return [], "command uses a subshell/group — execution context is not statically knowable"
        if tok in _SCOPE_OPERATORS:
            segments.append((cur, tok))
            cur = []
            continue
        cur.append(tok)
    segments.append((cur, ""))
    return [(argv, op) for argv, op in segments if argv or op], None


def _cd_target(argv: List[str]) -> Optional[str]:
    """Directory a ``cd`` segment moves to, or None when it is not resolvable.

    Only the literal forms are resolved. ``cd -`` (previous dir), ``cd $VAR``
    and anything with extra operands are deliberately unresolved — a scope that
    guessed here would be measuring the wrong directory.
    """
    if len(argv) == 1:
        return os.path.expanduser("~")
    if len(argv) != 2:
        return None
    target = argv[1]
    if target == "-" or target.startswith("$") or "$" in target:
        return None
    return target


def _resolve_dir(raw: str, cwd: str) -> List[str]:
    """Absolute forms of ``raw`` interpreted relative to ``cwd``.

    Returns BOTH the lexically-normalized path and its ``realpath``. Both must
    land in scope for a grant to apply: normalizing alone lets
    ``<store>/../../..`` escape, and realpath alone lets a scope pattern be
    dodged by a symlink planted inside the scope — which the grantee can do,
    since ``ln -s`` / ``mkdir`` / ``git init`` are all allowed unattended
    (review §5). The grantee-can-write-inside-the-scope case is the threat
    model, not a cooperative caller.
    """
    expanded = os.path.expanduser(raw)
    if not os.path.isabs(expanded):
        expanded = os.path.join(cwd, expanded)
    normalized = os.path.normpath(expanded)
    out = [normalized]
    try:
        real = os.path.realpath(normalized)
    except OSError:
        return out
    if real != normalized:
        out.append(real)
    return out


def command_scope_dirs(
    command: str,
    cwd: str,
    pattern: Optional[str] = None,
) -> Tuple[List[str], Optional[str]]:
    """Directories the rule-matching parts of ``command`` would act on.

    Returns ``(dirs, unscopeable)``. ``unscopeable`` is a reason string when the
    answer cannot be established — the caller must then NOT apply a scoped
    grant. ``dirs`` holds absolute paths (normalized and, where different,
    realpath'd); EVERY one of them must be in scope for the grant to apply
    (all-paths semantics, matching ``is_command_path_allowed``).

    Three independent selectors decide which repo a git command touches — the
    working directory, ``-C``, and ``--git-dir``/``--work-tree`` — so all three
    are read, and a command that names both an in-scope and an out-of-scope one
    is refused on the out-of-scope one.

    Only the segments the rule's own ``pattern`` matches are considered, so an
    innocuous tail (``git -C <store> commit -m x && echo done``) does not drag
    the session cwd into the scope test.

    Reads the RAW command, never a normalized haystack — so it is independent
    of #913's land order (the orchestrator ruling keeps the raw command
    reachable precisely so this stays true).
    """
    if pattern and pattern.startswith("ambiguous:"):
        return [], pattern.split(":", 1)[1] or "unverifiable command"

    obf = detect_obfuscation(command)
    if obf:
        return [], obf

    segments, split_err = _scope_segments(command)
    if split_err:
        return [], split_err
    if not segments:
        return [], "no command to evaluate"

    dirs: List[str] = []
    considered = 0
    current_dir = cwd

    for argv, following_op in segments:
        argv = _strip_assignments(argv)
        if not argv:
            continue
        head = os.path.basename(argv[0])

        if head in _CWD_CHANGING:
            # A `cd` only pins the directory for what follows when the shell
            # guarantees it ran AND succeeded — i.e. when `&&` joins them. With
            # `;` the next segment runs even if the `cd` failed, so it could
            # execute in either directory and we will not pick one.
            if head != "cd":
                return [], f"command uses {head} — directory stack is not statically knowable"
            if following_op != "&&":
                return [], (
                    f"`cd` is joined by '{following_op or 'nothing'}' rather than '&&', so the "
                    "directory the next command runs in is not statically knowable"
                )
            target = _cd_target(argv)
            if target is None:
                return [], "`cd` target is not a literal path"
            resolved = _resolve_dir(target, current_dir)
            # `cd` through a symlink leaves the shell's logical cwd at the
            # symlink path, so track the lexical form; the realpath form is
            # still checked below via _resolve_dir on the acting segment.
            current_dir = resolved[0]
            continue

        is_git = head == "git"
        git_dirs, stripped = (git_global_dirs(argv) if is_git else ([], argv))

        if pattern:
            # Match the rule against BOTH the segment as written and its
            # git-global-stripped form. The first is what matches today; the
            # second is what will match once #913 normalizes those options away
            # before rule matching. Handling both keeps scope evaluation
            # correct on either side of that change.
            haystacks = [" ".join(argv), " ".join(stripped)]
            try:
                if not any(re.search(pattern, h, re.IGNORECASE) for h in haystacks):
                    continue
            except re.error:
                return [], "rule pattern is not a usable regex"
        considered += 1

        if head in _INDIRECT_RUNNERS:
            return [], f"command runs through {head} — target directory is not statically knowable"

        if git_dirs:
            for d in git_dirs:
                dirs.extend(_resolve_dir(d, current_dir))
        else:
            dirs.extend(_resolve_dir(".", current_dir))

    if pattern and considered == 0:
        # The rule matched the command as a whole but no individual segment —
        # e.g. it matched inside an `sh -c` payload that `masked_subcommands`
        # re-scanned. We cannot say which directory that would touch.
        return [], "no subcommand matched the rule — target directory is not statically knowable"
    if not dirs:
        return [], "no target directory could be determined"
    # Stable order, no duplicates.
    return sorted(set(dirs)), None


_GLOB_CHARS = set("*?[")


def _scope_variants(scope_pattern: str) -> List[str]:
    """The scope pattern, plus a form with its literal prefix realpath'd.

    Resolve BOTH sides before comparing (review §5). The candidate path is
    offered in normalized and realpath'd form; the scope needs the same
    treatment or a scope rooted under a symlinked directory (``~/.claude`` ->
    elsewhere) would reject its own legitimate contents. Only the literal
    prefix up to the first glob character can be resolved — the rest is a
    pattern, not a path.
    """
    expanded = os.path.normpath(os.path.expanduser(scope_pattern).rstrip("/"))
    variants = [expanded]
    idx = next((i for i, ch in enumerate(expanded) if ch in _GLOB_CHARS), None)
    literal = expanded if idx is None else expanded[:idx].rsplit("/", 1)[0]
    if not literal or not os.path.isabs(literal):
        return variants
    try:
        real = os.path.realpath(literal)
    except OSError:
        return variants
    if real != literal:
        variants.append(real + expanded[len(literal):])
    return variants


def path_in_scope(path: str, scope_pattern: str) -> bool:
    """True when ``path`` is the directory ``scope_pattern`` names, or under it.

    ``*`` matches within one path segment, ``**`` crosses segments — the same
    reading as the rest of the rule files. Matching is exact (no case folding):
    a scope is a security boundary, and on a case-insensitive filesystem a
    permissive fold is the wrong direction to be wrong in.
    """
    normalized = os.path.normpath(path)
    for variant in _scope_variants(scope_pattern):
        if not variant:
            continue
        regex = ""
        i = 0
        while i < len(variant):
            ch = variant[i]
            if ch == "*":
                if variant[i:i + 2] == "**":
                    regex += ".*"
                    i += 2
                    continue
                regex += "[^/]*"
            elif ch == "?":
                regex += "[^/]"
            else:
                regex += re.escape(ch)
            i += 1
        try:
            if re.fullmatch(regex + r"(?:/.*)?", normalized):
                return True
        except re.error:
            continue
    return False


def unattended_grant_allows(
    rule_id: Optional[str],
    command: str,
    grants: Dict[str, List[List[str]]],
    cwd: str,
    pattern: Optional[str] = None,
    scopeable: bool = True,
) -> Tuple[bool, str]:
    """Does an unattended grant permit this ``ask``-tier command? ``(allowed, why)``.

    ``why`` is written to be read by a human in the block message — a refused
    scoped grant must say what it granted and what the command targeted, or the
    host is back to debugging a nightly timeout.

    ``scopeable=False`` declares that ``command`` has no filesystem target to
    measure a scope against — the MCP hook's synthesized ``agentwire email
    --to …`` is a tool invocation, not a command that touches a directory.
    A scoped grant then REFUSES rather than silently measuring the scope
    against the session cwd, which would have nothing to do with what the tool
    actually does.
    """
    if not rule_id:
        return False, "the matched rule has no id, so no grant can name it"
    scopes = grants.get(rule_id)
    if scopes is None:
        return False, f"rule '{rule_id}' is not on the unattended allowlist"
    if any(not s for s in scopes):
        return True, f"rule '{rule_id}' is granted unattended (unscoped)"

    flat = [p for s in scopes for p in s]
    if not scopeable:
        return False, (
            f"rule '{rule_id}' is granted only under {', '.join(flat)}, and this "
            f"action has no filesystem target to measure that scope against"
        )
    dirs, unscopeable = command_scope_dirs(command, cwd, pattern=pattern)
    if unscopeable:
        return False, (
            f"rule '{rule_id}' is granted only under {', '.join(flat)}, and this "
            f"command's target directory cannot be established ({unscopeable})"
        )
    outside = [d for d in dirs if not any(path_in_scope(d, p) for p in flat)]
    if outside:
        return False, (
            f"rule '{rule_id}' is granted only under {', '.join(flat)}, but this "
            f"command targets {', '.join(outside)}"
        )
    return True, (
        f"rule '{rule_id}' is granted under {', '.join(flat)}; "
        f"this command targets {', '.join(dirs)}"
    )


def load_safety_config(
    global_config_path: Optional[Path] = None,
    cwd: Optional[str] = None,
) -> Dict[str, Any]:
    """Resolve the effective safety knobs from the dedicated damage-control files.

    The kill switch and rule knobs live in HOST-OWNED, agent-unwritable files
    (see ``is_protected_control_plane``) — never in ``config.yaml`` /
    ``.agentwire.yml``, which the policed agent can edit:

      * Global:  ``~/.agentwire/damagecontrol.yml``
      * Project: ``.damagecontrol.yml`` (nearest, walking up from ``cwd``)

    Each holds top-level ``enabled`` / ``disabled_rules`` / ``unattended_allow``.
    Returns ``{enabled, disabled_rules, unattended_allow}``. A project
    ``.damagecontrol.yml`` may both loosen AND tighten ``enabled`` (it simply
    wins); ``disabled_rules`` / ``unattended_allow`` are merged (set-union).

    Fail-secure: a missing/unreadable/yaml-less global file ⇒ ``enabled: true``.
    """
    enabled = True
    disabled_rules: List[str] = []
    unattended_allow: List[str] = []
    project_enabled: Optional[bool] = None
    if not yaml:
        return {"enabled": enabled, "disabled_rules": disabled_rules,
                "unattended_allow": unattended_allow}

    def _absorb(data: Any) -> Optional[bool]:
        """Pull knobs from a parsed policy doc; return its ``enabled`` (or None)."""
        local_enabled: Optional[bool] = None
        if isinstance(data, dict):
            if "enabled" in data and data["enabled"] is not None:
                local_enabled = bool(data["enabled"])
            rules = data.get("disabled_rules", [])
            if isinstance(rules, list):
                disabled_rules.extend(str(r) for r in rules if r)
            allow = data.get("unattended_allow", [])
            if isinstance(allow, list):
                unattended_allow.extend(str(a) for a in allow if a)
        return local_enabled

    if global_config_path is None:
        global_config_path = Path.home() / ".agentwire" / "damagecontrol.yml"
    try:
        if global_config_path.exists():
            with open(global_config_path, "r") as f:
                gdata = yaml.safe_load(f) or {}
            genabled = _absorb(gdata)
            if genabled is not None:
                enabled = genabled
    except Exception:
        pass

    if cwd is None:
        cwd = os.environ.get("PWD", os.getcwd())
    current = os.path.abspath(cwd)
    while True:
        candidate = os.path.join(current, ".damagecontrol.yml")
        if os.path.isfile(candidate):
            try:
                with open(candidate, "r") as f:
                    pdata = yaml.safe_load(f) or {}
                project_enabled = _absorb(pdata)
            except Exception:
                pass
            break
        parent = os.path.dirname(current)
        if parent == current:
            break
        current = parent

    if project_enabled is not None:
        enabled = project_enabled

    return {
        "enabled": enabled,
        "disabled_rules": sorted(set(disabled_rules)),
        "unattended_allow": sorted(set(unattended_allow)),
    }


# ============================================================================
# PROTECTED CONTROL PLANE (escape-hatch- AND kill-switch-EXEMPT)
# ============================================================================
#
# Damage control reads its kill switch, its rules, and its own hook
# registration from files on disk. If the policed agent can write those files,
# it can disable safety, act, and re-enable — defeating everything (#466). So
# the WHOLE control plane is hard-protected: any write/edit/delete/move/chmod
# targeting one of these paths is BLOCKED, and — unlike every other rule — the
# ``# allow:`` escape hatch and the ``enabled: false`` kill switch do NOT
# override it. Only the user's ``allowedPaths`` allowlist can re-permit a path,
# because that is a human, host-side opt-in (the agent cannot add to it without
# editing a protected file, which is itself blocked).
#
# The guarantee: the agent only ever operates within the freedom the human
# preset. Loosening is always a host-side act.

PROTECTED_CONTROL_PLANE_PATHS = [
    "~/.agentwire/damagecontrol.yml",   # global kill switch + rule knobs
    "*.damagecontrol.yml",              # project kill switch + rule knobs (any dir)
    "~/.claude/settings.json",          # PreToolUse hook registration
    "~/.agentwire/hooks/damage-control/*.py",  # the hook scripts themselves
    "~/.claude/hooks/*",                # agentwire-owned Claude Code hooks
    "~/.agentwire/damage-control/*.yaml",      # the damage-control rule files
    # Execution-plane configs: agentwire runs strings from these files through
    # its OWN ``subprocess.run(..., shell=True)`` calls (scheduler gate commands
    # in scheduler.py, service healthchecks in services.py) — those subprocesses
    # do NOT traverse the Claude Code hook, so a policed agent that can write a
    # gate/healthcheck gets unguarded code execution on the next tick (a
    # confused-deputy escape). Treat them as control plane (#466 lockdown).
    "~/.agentwire/scheduler.yaml",      # scheduler gate commands run via shell
    "~/.agentwire/config.yaml",         # service healthcheck commands run via shell
    # Per-project task-EXECUTION config (#720): split out of ``.agentwire.yml``,
    # which is now purely declarative (type/roles/voice/parent/worktree) and
    # agent-writable again — it carries no exec vector. ``.agentwire.tasks.yml``
    # holds the ``tasks:`` block (pre/post/on_task_end/shell/unattended_allow),
    # which agentwire runs the same way (confused-deputy risk above), so it
    # stays protected. Authored via propose-and-promote: an agent drafts to the
    # UNPROTECTED ``.agentwire.tasks.proposed.yml`` staging file; a human reviews
    # (``agentwire tasks review``) and promotes (``agentwire tasks promote``) —
    # the agent never writes the live file. See ``agentwire/tasks_cli.py``.
    "*.agentwire.tasks.yml",            # project task-execution config (any dir)
]


def _protected_path_patterns() -> List[str]:
    """Protected paths in both ``~``-form and ``$HOME``-expanded form.

    Commands may reference either; including both ensures the regex/glob
    matchers catch e.g. ``/Users/me/.claude/settings.json`` and
    ``~/.claude/settings.json`` alike.
    """
    out: List[str] = []
    for p in PROTECTED_CONTROL_PLANE_PATHS:
        out.append(p)
        expanded = os.path.expanduser(p)
        if expanded != p:
            out.append(expanded)
    return out


def _matched_protected_pattern(file_path: str) -> Optional[str]:
    """The protected-path pattern that matches ``file_path``, if any."""
    for pat in _protected_path_patterns():
        if match_path(file_path, pat):
            return pat
    return None


def is_protected_control_plane(file_path: str) -> bool:
    """True if ``file_path`` is part of the damage-control control plane."""
    return _matched_protected_pattern(file_path) is not None


def _protected_reason(matched_pattern: str) -> str:
    """Block reason for a protected-control-plane hit, tailored to the path.

    ``.agentwire.tasks.yml`` has a real, host-side remedy (propose-and-promote,
    #720) — name it so the agent doesn't dead-end. Everything else keeps the
    generic "edit on the host" message.
    """
    if matched_pattern.endswith(".agentwire.tasks.yml"):
        return (
            "protected task-execution control-plane file (host-owned) — draft "
            "to .agentwire.tasks.proposed.yml instead, then ask the host to run "
            "`agentwire tasks review` and `agentwire tasks promote`"
        )
    return "protected control-plane file (host-owned; edit on the host)"


def check_protected_path(
    file_path: str,
    allowed_paths: List[Dict[str, Any]],
) -> Tuple[bool, str]:
    """Block edits/writes to a control-plane file unless the user allowlisted it.

    Used by the edit/write hooks. The allowlist (a human opt-in) may override;
    nothing else does.
    """
    matched = _matched_protected_pattern(file_path)
    if matched:
        if is_path_allowed_for_op(file_path, allowed_paths, "edit"):
            return False, ""
        return True, _protected_reason(matched)
    return False, ""


def check_protected_command(
    command: str,
    allowed_paths: List[Dict[str, Any]],
) -> Tuple[bool, str]:
    """Block a bash command that writes/edits/deletes a control-plane file.

    Mirrors the ``readOnlyPaths`` matcher but is escape-hatch- and
    kill-switch-exempt. The user's allowlist may re-permit a specific path.

    Matches against the raw command AND its normalized subcommands so quoting /
    escaping (``r\\m``, ``r''m``) can't sneak a write past the control-plane gate.
    """
    subcommands, _ambiguous = normalize_subcommands(command)
    haystacks = [command] + [s for s in subcommands if s and s != command]
    for path in _protected_path_patterns():
        for hay in haystacks:
            matched, reason = check_path_patterns(
                hay,
                path,
                READ_ONLY_BLOCKED + INTERPRETER_WRITE_PATTERNS,
                "protected control-plane path",
            )
            if matched:
                op = _infer_operation_from_reason(reason)
                if is_command_path_allowed(command, allowed_paths, op):
                    break
                return True, _protected_reason(path)
    return False, ""


# ============================================================================
# PROTECTED COMMANDS (escape-hatch- AND kill-switch-EXEMPT, like the protected
# control plane above, but keyed on COMMAND SHAPE rather than a file path)
# ============================================================================
#
# Some operations are dangerous no matter which file they touch — running
# them at all IS the confused-deputy escape, not merely writing a particular
# path. ``agentwire tasks promote`` is the first case (#720/#721 review):
# it's the host-trusted program that copies a vetted draft into the protected
# ``.agentwire.tasks.yml``. If a policed/unattended agent could just invoke
# the CLI itself, the file protection above is moot — so this, like the
# protected-path check, is evaluated before ``detect_escape_hatch`` and the
# kill switch, and has NO allowlist override (there's no legitimate reason
# for an agent to ever run this; unlike a path, there's nothing to allowlist
# it TO). This is defense in depth on TOP OF ``cmd_tasks_promote``'s own
# runtime refusal (unattended check + host-context gate in ``tasks_cli.py``)
# — that second gate is what actually closes the ``python3 -c
# "from agentwire.tasks_cli import cmd_tasks_promote; ..."`` bypass, since a
# raw interpreter call never matches a bash command pattern at all.

PROTECTED_COMMAND_PATTERNS: List[Tuple[str, str]] = [
    (
        r'\bagentwire\s+tasks\s+promote\b',
        "agentwire tasks promote writes the protected .agentwire.tasks.yml — "
        "host-only, run it from your own terminal (not through an agent).",
    ),
]


def check_protected_bash_command(command: str) -> Tuple[bool, str]:
    """Block a command matching a ``PROTECTED_COMMAND_PATTERNS`` entry.

    Unconditional — no allowlist override, no escape hatch, no kill switch
    (see module note above). These are COMMAND-PREFIX patterns, so — like the
    ``anchored`` tooldef bashToolPatterns (#675) — matched only against
    ``masked_subcommands``: quoting/escaping of the command itself still
    normalizes to the literal form (``agentwire tasks prom''ote`` can't sneak
    past), but quoted CONTENT (a commit message, an echo string) that merely
    *mentions* the phrase is masked out first, so it can't false-match.
    """
    haystacks = masked_subcommands(command)
    for pattern, reason in PROTECTED_COMMAND_PATTERNS:
        for hay in haystacks:
            try:
                if re.search(pattern, hay, re.IGNORECASE):
                    return True, reason
            except re.error:
                continue
    return False, ""


_ESCAPE_HATCH_RE = re.compile(r"#\s*allow:[ \t]*([^\n]+)", re.IGNORECASE)


def detect_escape_hatch(command: str) -> Optional[str]:
    """Return the reason if ``command`` contains a ``# allow: <reason>`` marker.

    Non-empty reason required; matches the rest of the comment line so the
    marker works on multi-line / chained commands too.
    """
    if not command:
        return None
    m = _ESCAPE_HATCH_RE.search(command)
    if not m:
        return None
    reason = m.group(1).strip()
    return reason or None


# ============================================================================
# SHELL-AWARE NORMALIZATION
# ============================================================================
#
# The bash matcher historically ran the rule regexes against the RAW command
# string. With no tokenization, trivial shell quoting/escaping defeated every
# rule: ``r\m -rf /x`` (backslash), ``r''m -rf /x`` (empty quotes),
# ``R=rm; $R -rf /x`` ($VAR indirection) all read as ALLOWED while literal
# ``rm -rf /x`` blocked. We now ALSO match against a normalized form where
# quotes/escapes are removed (via ``shlex``) and simple ``$VAR`` assignments are
# resolved, split per subcommand. Anything we cannot tokenize safely — command
# substitution (``$(...)`` / backticks), ``eval``, a ``base64 -d | sh`` pipeline,
# or unbalanced quotes — FAILS CLOSED (escalated to ``ask``, which the unattended
# resolver turns into a block).

_SUBSTITUTION_RE = re.compile(r"\$\(|`")
_EVAL_RE = re.compile(r"(?:^|[\s;&|({])eval(?:\s|$)")
_BASE64_PIPE_RE = re.compile(r"\bbase64\b[^\n|]*(?:-d|--decode)[^\n|]*\|", re.IGNORECASE)
_ASSIGN_RE = re.compile(
    r"(?:^|[\n;&|]|&&|\|\|)\s*([A-Za-z_]\w*)=('[^']*'|\"[^\"]*\"|[^\s;|&]*)"
)
_SHELL_OPERATORS = {";", "&&", "||", "|", "&", "\n", ";;", "|&"}


def detect_obfuscation(command: str) -> Optional[str]:
    """Return a reason string if ``command`` hides intent behind shell features.

    These constructs can smuggle a dangerous command past static matching, so we
    decline to reason about them and fail closed instead.
    """
    if _SUBSTITUTION_RE.search(command):
        return "command substitution"
    if _EVAL_RE.search(command):
        return "eval"
    if _BASE64_PIPE_RE.search(command):
        return "base64-decode pipeline"
    return None


def normalize_subcommands(command: str) -> Tuple[List[str], Optional[str]]:
    """Tokenize ``command`` and return ``(normalized_subcommands, ambiguous)``.

    ``normalized_subcommands`` is the per-subcommand argv re-joined with single
    spaces, after ``shlex`` has stripped quotes/escapes and simple ``$VAR``
    assignments earlier in the same command have been resolved. ``ambiguous`` is
    a reason string when the command can't be tokenized safely (and the caller
    should fail closed); it is ``None`` on success.
    """
    obf = detect_obfuscation(command)
    if obf:
        return [], obf

    # Resolve simple ``VAR=value`` assignments so ``R=rm; $R -rf`` normalizes to
    # ``rm -rf``. Only literal values (no nested expansion) are resolved.
    assigns: Dict[str, str] = {}
    for m in _ASSIGN_RE.finditer(command):
        assigns[m.group(1)] = m.group(2).strip("'\"")

    try:
        lex = shlex.shlex(command, posix=True, punctuation_chars=True)
        lex.whitespace_split = True
        tokens = list(lex)
    except ValueError:
        return [], "unbalanced quotes"

    def _resolve(tok: str) -> str:
        for name, val in assigns.items():
            tok = tok.replace("${%s}" % name, val).replace("$" + name, val)
        return tok

    subs: List[str] = []
    cur: List[str] = []
    for tok in tokens:
        if tok in _SHELL_OPERATORS:
            if cur:
                subs.append(" ".join(cur))
                cur = []
            continue
        cur.append(_resolve(tok))
    if cur:
        subs.append(" ".join(cur))
    return subs, None


#
# CONTENT MASKING (#675)
#
# Tooldef rules are COMMAND-PREFIX rules (``\bgh\s+pr\s+comment\b``), but the
# haystacks above include quoted argument text — so a commit message that
# merely *mentions* "gh pr comment" false-matches the rule. Anchored rules are
# therefore matched against MASKED subcommands instead: quoted spans that can
# only be content (a quoted token containing whitespace — a message, an echo
# string, a heredoc body) are replaced with a placeholder, while quoted
# single words are kept (``"gh" pr comment`` is still a real command) and
# ``sh -c "…"`` payloads are recursively re-scanned as commands.

_MASK = "\x00"
_HEREDOC_RE = re.compile(r"<<-?\s*(['\"]?)([A-Za-z_]\w+)\1")
_SHELL_NAMES = {"sh", "bash", "zsh", "dash", "ksh"}
_ASSIGN_TOKEN_RE = re.compile(r"^[A-Za-z_]\w*=")


#
# GIT GLOBAL OPTIONS (#913)
#
# Every git rule — both the hand-written ``bashToolPatterns`` in the rule YAMLs
# (``\bgit\s+push\s+--force\b``) and the tooldef-generated ones from
# ``_cmd_to_regex`` (``\bgit\s+commit\b``) — assumes the subcommand sits
# adjacent to ``git``. It doesn't have to: ``git -C <dir> <cmd>`` is the
# idiomatic way to operate on a repo without ``cd``, and ``\s+`` cannot span
# ``-C /repo``. That single assumption defeated EVERY git rule, force-push and
# hard-reset included.
#
# Rather than teach ~15 patterns about ``-C`` (and miss the next one written),
# we emit an extra haystack per subcommand with git's global options removed,
# so present and future git rules inherit the fix for free.
#
# This is strictly ADDITIVE — the un-stripped forms stay in the haystack list.
# A rule that legitimately cares WHICH repo is being touched (a path rule, an
# allowlist check) still sees ``-C /repo`` in the raw command; stripping can
# only ever remove tokens, so the extra variant can introduce no path a rule
# didn't already see.
#
# Membership below is measured against real git (2.50.1), not assumed:
# ``-C``/``-c`` require a SEPARATE argument (``-C/tmp`` is rejected by git, so
# the attached form is not a bypass); ``--git-dir``/``--work-tree``/
# ``--namespace``/``--config-env``/``--attr-source`` accept both the ``=`` and
# the space form; ``--exec-path`` without ``=`` prints and exits, so it
# consumes nothing.

_GIT_GLOBAL_VALUE_OPTS = {
    "-C", "-c", "--git-dir", "--work-tree", "--namespace",
    "--config-env", "--attr-source",
}

_GIT_GLOBAL_FLAGS = {
    "-p", "-P", "--paginate", "--no-pager", "--bare", "--exec-path",
    "--no-optional-locks", "--no-replace-objects", "--no-lazy-fetch",
    "--no-advice", "--literal-pathspecs", "--glob-pathspecs",
    "--noglob-pathspecs", "--icase-pathspecs", "--html-path", "--man-path",
    "--info-path",
}

# Tokens allowed to precede ``git`` while still counting as a git invocation
# (``sudo git -C /repo push --force`` must normalize too — the un-stripped
# ``sudo git push --force`` already matches, so leaving this out would keep the
# very inconsistency the rule is meant to remove). ``_MASK`` covers a leading
# ``VAR=value`` assignment, which ``masked_subcommands`` has already masked.
#
# The exclusion is about ARITY AS WRITTEN, not about which wrapper it is. Every
# name below is covered when it appears BARE; the same name carrying its own
# arguments is not — ``xargs git …`` normalizes, ``xargs -n1 git …`` does not,
# and likewise ``nice`` vs ``nice -n 5``. The wrapper's argument is an
# unrecognized token, the scan bails, and no variant is produced, so that form
# keeps the bypass.
#
# Naming wrappers rather than arity is precisely the error this comment used to
# make: it listed ``xargs -n1`` as an excluded WRAPPER, which read as excluding
# ``xargs``, and bare ``xargs git -C /repo push --force`` stayed a live bypass
# under a comment implying otherwise.
#
# Argument-carrying forms are out of scope rather than half-handled, because
# consuming them means modelling each wrapper's own grammar — this bug's
# mistake at one remove. Failure there is a MISSING haystack, never an
# over-strip: we add nothing rather than stripping too much.
_GIT_INVOCATION_PREFIXES = {
    "sudo", "doas", "env", "command", "time", "nice", "nohup", "xargs", _MASK,
}


def _strip_git_global_options(words: List[str]) -> Optional[List[str]]:
    """Return ``words`` with git's global options removed, or ``None``.

    ``None`` means "no normalized variant to add": not a git invocation, no
    global options present, or nothing left after the options.
    """
    git_idx = None
    for i, w in enumerate(words):
        if w.rsplit("/", 1)[-1] == "git":
            git_idx = i
            break
        if w not in _GIT_INVOCATION_PREFIXES and not _ASSIGN_TOKEN_RE.match(w):
            return None
    if git_idx is None:
        return None

    i = git_idx + 1
    stripped = False
    while i < len(words):
        word = words[i]
        if word in _GIT_GLOBAL_VALUE_OPTS:
            # Consumes the following argument along with the flag — dropping
            # only the flag would leave the value sitting where the subcommand
            # should be, and the rule would still miss.
            i += 2
            stripped = True
            continue
        if word in _GIT_GLOBAL_FLAGS:
            i += 1
            stripped = True
            continue
        base = word.split("=", 1)[0]
        if "=" in word and (base in _GIT_GLOBAL_VALUE_OPTS or base in _GIT_GLOBAL_FLAGS):
            i += 1
            stripped = True
            continue
        # MAINTENANCE EDGE: an option git adds after 2.50.1 is an unrecognized
        # token here, so the scan stops and the partial strip leaves the
        # subcommand still out of reach — ``git --future-opt -C /r push --force``
        # reads as allow. Not exploitable today (git rejects the unknown option
        # itself), and nothing in the suite fails when git grows one, so
        # re-measure both sets on a git upgrade. Stopping is deliberate: the
        # alternative — treating anything option-shaped as strippable — would
        # let an unknown value-taking option swallow the subcommand.
        break

    if not stripped or i >= len(words):
        return None
    return words[: git_idx + 1] + words[i:]


def git_normalized_haystacks(command: str) -> List[str]:
    """Return the git-global-options-stripped forms of ``command``, if any.

    This is an ADDITIVE haystack, kept alongside the raw and masked lists
    rather than rewriting either, and fed to ALL rules — anchored and
    unanchored alike. Both halves of that sentence are load-bearing.

    ADDITIVE, because stripping is DELETION. ``-c <k>=<v>`` values are executed
    by git (``core.sshCommand``, ``core.pager``, ``alias.*``,
    ``core.fsmonitor``), so the value is a command payload sitting in the
    haystack. Where a content rule DOES match that payload — the deletion rules
    catch an ``rm``-shaped one — rewriting a haystack in place would delete it
    from the only place it appears and turn a block into an allow: the fix
    creating a worse bug than the one it closes. Coverage of these payloads is
    partial, not a guarantee this function provides: a ``curl … | sh`` value is
    allowed with or without normalization. Additivity preserves whatever
    coverage exists; it does not create any.
    (Note it is deletion, not masking, that would lose them: ``masked_subcommands``
    blanks a token only when it is FULLY quoted, and ``core.pager='…'`` carries
    an unquoted ``core.pager=`` prefix, so the payload survives masking and is
    visible in both existing haystacks.) A rule that legitimately cares WHICH
    repo is being touched — a path rule, an unattended path scope (#914) — reads
    those same un-stripped forms: the ``-C`` argument is set aside, not discarded.

    FED TO ALL RULES, because the intersection "must stay unanchored AND
    global-option-bypassable" is unreachable by a two-way split. Rules that are
    deliberately unanchored to catch an ssh-wrapped form would never see
    normalization and would stay permanently bypassed.

    Masking is applied to the new path exactly as it is to the old one — the
    variant is built from the MASKED token lists, so the anchored path receives
    the normalized command masked, rather than being handed an unmasked
    haystack that would reopen #675 on every anchored git rule.
    """
    out: List[str] = []
    for words in _masked_subcommand_words(command):
        normalized = _strip_git_global_options(words)
        if normalized is not None:
            joined = " ".join(normalized)
            if joined not in out:
                out.append(joined)
    return out


def _strip_heredoc_bodies(command: str) -> str:
    """Remove heredoc body lines (``<<EOF … EOF``) — they are content."""
    m = _HEREDOC_RE.search(command)
    if not m:
        return command
    delim = m.group(2)
    nl = command.find("\n", m.end())
    if nl == -1:
        return command
    lines = command[nl + 1:].split("\n")
    for i, line in enumerate(lines):
        if line.strip() == delim:
            rest = "\n".join(lines[i + 1:])
            return command[:nl + 1] + _strip_heredoc_bodies(rest)
    # Unterminated heredoc: everything after the marker is body.
    return command[:nl + 1]


def _scan_masked_tokens(command: str) -> List[List[Tuple[str, bool]]]:
    """Split ``command`` into subcommands of ``(token_text, fully_quoted)``.

    Quotes/escapes are resolved into the token text (so ``g''h`` -> ``gh``);
    ``fully_quoted`` is True when no character of the token was unquoted.
    """
    subs: List[List[Tuple[str, bool]]] = []
    cur: List[Tuple[str, bool]] = []
    buf: List[str] = []
    has_unquoted = False
    has_any = False

    def end_token() -> None:
        nonlocal buf, has_unquoted, has_any
        if has_any:
            cur.append(("".join(buf), not has_unquoted))
        buf, has_unquoted, has_any = [], False, False

    def end_sub() -> None:
        nonlocal cur
        end_token()
        if cur:
            subs.append(cur)
            cur = []

    i, n = 0, len(command)
    while i < n:
        c = command[i]
        if c == "'":
            j = command.find("'", i + 1)
            if j == -1:
                j = n
            buf.append(command[i + 1:j])
            has_any = True
            i = j + 1
        elif c == '"':
            j = i + 1
            out: List[str] = []
            while j < n and command[j] != '"':
                if command[j] == "\\" and j + 1 < n and command[j + 1] in '"\\$`':
                    out.append(command[j + 1])
                    j += 2
                else:
                    out.append(command[j])
                    j += 1
            buf.append("".join(out))
            has_any = True
            i = j + 1
        elif c == "\\" and i + 1 < n:
            buf.append(command[i + 1])
            has_unquoted = True
            has_any = True
            i += 2
        elif c in " \t":
            end_token()
            i += 1
        elif c in ";\n":
            end_sub()
            i += 1
        elif c in "&|":
            end_sub()
            while i < n and command[i] in "&|":
                i += 1
        else:
            buf.append(c)
            has_unquoted = True
            has_any = True
            i += 1
    end_sub()
    return subs


def masked_subcommands(command: str) -> List[str]:
    """Return per-subcommand strings with content-only quoted spans masked.

    Used for command-prefix (``anchored``) rules so quoted argument text —
    commit messages, echo strings, heredoc bodies — cannot false-match a
    command rule, while quoting obfuscation of the command itself still
    normalizes to the literal form.
    """
    return [" ".join(words) for words in _masked_subcommand_words(command)]


def _masked_subcommand_words(command: str) -> List[List[str]]:
    """Token-list form of :func:`masked_subcommands`, before joining.

    Split out so the ``sh -c "…"`` recursion and the git normalization both
    operate on tokens — re-splitting a joined string would lose the token
    boundaries a ``-C "/my dir"`` argument depends on.
    """
    command = _strip_heredoc_bodies(command)

    assigns: Dict[str, str] = {}
    for m in _ASSIGN_RE.finditer(command):
        assigns[m.group(1)] = m.group(2).strip("'\"")

    def _resolve(tok: str) -> str:
        for name, val in assigns.items():
            tok = tok.replace("${%s}" % name, val).replace("$" + name, val)
        return tok

    results: List[List[str]] = []
    for toks in _scan_masked_tokens(command):
        words: List[str] = []
        prev = ""
        for text, fully_quoted in toks:
            resolved = _resolve(text)
            is_content = fully_quoted and (not resolved or any(ch in " \t\n" for ch in resolved))
            if not words and _ASSIGN_TOKEN_RE.match(resolved):
                # Leading VAR=value assignment — its value is data here (the
                # assigns table already handles later ``$VAR`` expansion).
                words.append(_MASK)
                prev = _MASK
                continue
            if is_content:
                # A ``sh -c "…"`` payload is a command, not content — rescan.
                if (
                    words
                    and prev.startswith("-")
                    and "c" in prev
                    and words[0].rsplit("/", 1)[-1] in _SHELL_NAMES
                ):
                    results.extend(_masked_subcommand_words(resolved))
                words.append(_MASK)
                prev = _MASK
            else:
                words.append(resolved)
                prev = resolved
        if words and any(w != _MASK for w in words):
            results.append(words)
    return results


# ============================================================================
# DECISION LADDERS
# ============================================================================


def check_command(command: str, config: Dict[str, Any]) -> Dict[str, Any]:
    """Decide whether a bash command should be allowed/blocked/asked.

    Returns ``{decision, reason, pattern, command}`` plus optional ``id``,
    ``escape_reason``, ``escape``, ``disabled``.

    Order:
      0. Protected control plane → BLOCK (escape-hatch- AND kill-switch-exempt;
         only the user's allowlist re-permits) — runs FIRST so an agent can't
         self-authorize a write to the files that gate everything else.
      0.5. Protected commands → BLOCK (same exemption, no allowlist override —
         a command whose mere invocation is the escape, not a path it touches).
      1. Escape hatch (``# allow: <reason>``) → ALLOW (escape=True)
      2. Kill switch (``config["safety"]["enabled"] is False``) → ALLOW (disabled=True)
      3. Hard-blocked bash patterns (skip if ``id`` in ``disabled_rules``)
      4. Ask patterns
      5. Bypassable bash patterns → check allowlist for required operation
      6. zeroAccessPaths → check allowlist with ``read`` permission
      7. readOnlyPaths → match against READ_ONLY_BLOCKED operation patterns
      8. noDeletePaths → match against NO_DELETE_BLOCKED patterns
    """
    safety_cfg = config.get("safety", {}) if isinstance(config.get("safety"), dict) else {}
    disabled_rules = set(safety_cfg.get("disabled_rules", []) or [])
    is_enabled = safety_cfg.get("enabled", True)

    allowed = load_allowed_paths(config)

    # Protected control plane FIRST — before the escape hatch and the kill
    # switch. An agent must never be able to self-authorize a write to the
    # files that define safety itself (#466).
    prot_blocked, prot_reason = check_protected_command(command, allowed)
    if prot_blocked:
        return {
            "decision": "block",
            "reason": prot_reason,
            "pattern": "protectedControlPlane",
            "command": command,
            "protected": True,
        }

    # Protected COMMANDS — same tier, same reason (an agent-invoked
    # `agentwire tasks promote` is the confused-deputy escape itself, not a
    # path it happens to touch).
    cmd_blocked, cmd_reason = check_protected_bash_command(command)
    if cmd_blocked:
        return {
            "decision": "block",
            "reason": cmd_reason,
            "pattern": "protectedCommand",
            "command": command,
            "protected": True,
        }

    # Parser unavailable ⇒ no rules loaded ⇒ fail closed (block), before the
    # escape hatch / kill switch can wave it through.
    if config.get("_parser_unavailable"):
        return {
            "decision": "block",
            "reason": str(config["_parser_unavailable"]),
            "pattern": "parserUnavailable",
            "command": command,
        }

    escape_reason = detect_escape_hatch(command)
    if escape_reason:
        return {
            "decision": "allow",
            "reason": f"Escape hatch: {escape_reason}",
            "pattern": None,
            "command": command,
            "escape": True,
            "escape_reason": escape_reason,
        }

    if is_enabled is False:
        return {
            "decision": "allow",
            "reason": "safety disabled",
            "pattern": None,
            "command": command,
            "disabled": True,
        }

    bash_patterns = config.get("bashToolPatterns", [])
    zero_access = config.get("zeroAccessPaths", [])
    read_only = config.get("readOnlyPaths", [])
    no_delete = config.get("noDeletePaths", [])

    # Match rules against the raw command AND its normalized subcommands, so a
    # quoting/escaping/$VAR trick (``r\m``, ``r''m``, ``R=rm; $R -rf``) is caught
    # the same as the literal form. ``ambiguous`` is set when the command hides
    # behind substitution/eval/base64-pipe/unbalanced-quotes — we fail closed to
    # ``ask`` at the end (the unattended resolver turns that into a block).
    subcommands, ambiguous = normalize_subcommands(command)
    haystacks = [command] + [s for s in subcommands if s and s != command]
    # Anchored (command-prefix) rules match only masked subcommands, so quoted
    # argument text — commit messages, echo strings — can't false-match (#675).
    masked_haystacks = masked_subcommands(command)
    # Third variant (#913): git with its global options stripped, so a rule
    # written as ``\bgit\s+push\b`` still sees the subcommand behind
    # ``git -C <dir>``. ADDED to whichever list a rule already reads — neither
    # is rewritten — so the raw command stays reachable for the rules that need
    # it, and derived from the masked tokens so it can never make quoted content
    # matchable. Both halves are load-bearing: bundled git rules are anchored
    # (masked path), while the rules installed on this machine carry zero
    # ``anchored: true`` and read the raw path, so covering one alone would fix
    # the bypass in only one of the two rule sets in play.
    git_haystacks = git_normalized_haystacks(command)

    def _search(pat: str, hays: List[str]) -> bool:
        for hay in hays:
            try:
                if re.search(pat, hay, re.IGNORECASE):
                    return True
            except re.error:
                return False
        return False

    bypassable_matches: List[Tuple[str, str, Optional[str]]] = []

    for pattern_obj in bash_patterns:
        if not isinstance(pattern_obj, dict):
            continue
        rule_id = pattern_obj.get("id")
        if rule_id and rule_id in disabled_rules:
            continue
        pattern = pattern_obj.get("pattern", "")
        reason = pattern_obj.get("reason", "Matched pattern")
        should_ask = pattern_obj.get("ask", False)
        bypassable = pattern_obj.get("bypassable", False)
        anchored = pattern_obj.get("anchored", False)
        try:
            base = masked_haystacks if anchored else haystacks
            if _search(pattern, base + git_haystacks):
                if should_ask:
                    return {
                        "decision": "ask",
                        "reason": reason,
                        "pattern": pattern,
                        "command": command,
                        "id": rule_id,
                    }
                elif bypassable:
                    bypassable_matches.append((pattern, reason, rule_id))
                else:
                    return {
                        "decision": "block",
                        "reason": reason,
                        "pattern": pattern,
                        "command": command,
                        "id": rule_id,
                    }
        except re.error:
            continue

    for pattern, reason, rule_id in bypassable_matches:
        operation = _infer_operation_from_reason(reason)
        if not is_command_path_allowed(command, allowed, operation):
            return {
                "decision": "block",
                "reason": reason,
                "pattern": pattern,
                "command": command,
                "id": rule_id,
            }

    for path in zero_access:
        if any(matches_path_in_command(path, hay) for hay in haystacks):
            if is_command_path_allowed(command, allowed, "read"):
                continue
            return {
                "decision": "block",
                "reason": f"Zero-access path: {path}",
                "pattern": f"zeroAccessPath: {path}",
                "command": command,
            }

    for path in read_only:
        op = None
        for hay in haystacks:
            matched, reason = check_path_patterns(hay, path, READ_ONLY_BLOCKED, "read-only path")
            if matched:
                op = _infer_operation_from_reason(reason)
                break
        if op is not None:
            if is_command_path_allowed(command, allowed, op):
                continue
            return {
                "decision": "block",
                "reason": f"Read-only path: {path}",
                "pattern": f"readOnlyPath: {path}",
                "command": command,
            }

    for path in no_delete:
        if any(
            check_path_patterns(hay, path, NO_DELETE_BLOCKED, "no-delete path")[0]
            for hay in haystacks
        ):
            if is_command_path_allowed(command, allowed, "delete"):
                continue
            return {
                "decision": "block",
                "reason": f"No-delete path: {path}",
                "pattern": f"noDeletePath: {path}",
                "command": command,
            }

    # Nothing matched. If the command hid behind substitution/eval/etc. we could
    # not verify it statically — fail closed to ``ask`` (a block when unattended).
    if ambiguous:
        return {
            "decision": "ask",
            "reason": f"Unverifiable command ({ambiguous}) — confirm before running",
            "pattern": f"ambiguous:{ambiguous}",
            "command": command,
            "id": "core.ambiguous-command",
        }

    return {
        "decision": "allow",
        "reason": "No patterns matched",
        "pattern": None,
        "command": command,
    }


def check_path(file_path: str, config: Dict[str, Any]) -> Tuple[bool, str]:
    """File-path-only check used by edit/write hooks. Returns ``(blocked, reason)``.

    The protected control plane is checked FIRST, before the kill switch — the
    files that gate safety stay agent-unwritable even when safety is disabled;
    only the user's allowlist re-permits them (#466).
    """
    allowed = load_allowed_paths(config)

    prot_blocked, prot_reason = check_protected_path(file_path, allowed)
    if prot_blocked:
        return True, prot_reason

    safety_cfg = config.get("safety", {}) if isinstance(config.get("safety"), dict) else {}
    if safety_cfg.get("enabled", True) is False:
        return False, ""

    if is_path_allowed_for_op(file_path, allowed, "edit"):
        return False, ""

    for zero_path in config.get("zeroAccessPaths", []):
        if match_path(file_path, zero_path):
            return True, f"zero-access path {zero_path} (no operations allowed)"

    for readonly in config.get("readOnlyPaths", []):
        if match_path(file_path, readonly):
            return True, f"read-only path {readonly}"

    return False, ""


def check_read_path(file_path: str, config: Dict[str, Any]) -> Tuple[bool, str]:
    """File-path-only check for content-reading tools (Read/Grep/Glob).

    The Bash/Edit/Write hooks never see native ``Read``/``Grep``/``Glob`` tool
    calls, so a ``zeroAccessPaths`` secret (``~/.agentwire/.env``, ``~/.ssh/id_rsa``,
    ``*.pem``) could be exfiltrated by reading it directly. Claude Code fires a
    blocking ``PreToolUse`` hook for these tools too, so the read-tool hook runs
    ``file_path`` through this check and blocks a zero-access read.

    Only ``zeroAccessPaths`` deny reads — ``readOnlyPaths`` are readable by
    definition, and the control plane is host-owned config the agent may read
    (only its *writes* are blocked). The kill switch disables this like any other
    rule; the allowlist (a human opt-in) re-permits a specific read.
    """
    allowed = load_allowed_paths(config)
    if is_path_allowed_for_op(file_path, allowed, "read"):
        return False, ""

    safety_cfg = config.get("safety", {}) if isinstance(config.get("safety"), dict) else {}
    if safety_cfg.get("enabled", True) is False:
        return False, ""

    for zero_path in config.get("zeroAccessPaths", []):
        if match_path(file_path, zero_path):
            return True, f"zero-access path {zero_path} (no read access)"

    return False, ""
# === END GENERATED ===


# ============================================================================
# HOOK ENTRY POINT
# ============================================================================


def _resolve_rules_dir() -> Path:
    """User override (~/.agentwire/damage-control/) wins; else bundled rules/."""
    user_dir = Path(os.environ.get("AGENTWIRE_DIR", os.path.expanduser("~/.agentwire")))
    user_rules = user_dir / "damage-control"
    if user_rules.exists() and any(user_rules.glob("*.yaml")):
        return user_rules
    return Path(__file__).parent / "rules"


def _resolve_tooldefs_dir():
    """User tooldefs (~/.agentwire/tooldefs/) win; else bundled."""
    user_dir = Path(os.environ.get("AGENTWIRE_DIR", os.path.expanduser("~/.agentwire")))
    user_tooldefs = user_dir / "tooldefs"
    if user_tooldefs.exists() and any(user_tooldefs.glob("*.yaml")):
        return user_tooldefs
    bundled = Path(__file__).parent.parent.parent / "tooldefs"
    return bundled if bundled.exists() else None


def _notify_unattended_block(command: str, reason: str, rule_id: str | None) -> None:
    """Fire-and-forget: email the owner that an unattended action was blocked.

    The hook is a PEP 723 script (pyyaml-only) and can't import the agentwire
    package, so it shells out to the installed CLI, which emails via the same
    Resend wiring usage-limit recovery uses. Detached + non-blocking so SMTP
    never sits on the hook's hot path; failures are swallowed (the block has
    already fired and is audit-logged regardless).
    """
    import subprocess
    try:
        subprocess.Popen(
            ["agentwire", "safety", "notify-unattended-block",
             "--reason", reason or "",
             "--rule-id", rule_id or "",
             "--command", command[:500]],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            stdin=subprocess.DEVNULL,
            start_new_session=True,
        )
    except Exception:
        pass


def main() -> None:
    config = load_config(_resolve_rules_dir(), _resolve_tooldefs_dir())
    config["safety"] = load_safety_config()

    try:
        input_data = json.load(sys.stdin)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON input: {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error reading input: {e}", file=sys.stderr)
        sys.exit(1)

    tool_name = input_data.get("tool_name", "")
    tool_input = input_data.get("tool_input", {})
    # Claude Code passes ``permission_mode`` in the hook input. Two modes
    # indicate the user has explicitly opted out of ask-escalation friction:
    #   - "bypassPermissions" → --dangerously-skip-permissions
    #   - "auto"              → autonomous /loop or similar auto mode
    # Hard blocks still fire either way; ``ask:true`` patterns become allow.
    permission_mode = input_data.get("permission_mode", "")
    bypass_modes = {"bypassPermissions", "auto"}

    if tool_name != "Bash":
        sys.exit(0)

    command = tool_input.get("command", "")
    if not command:
        sys.exit(0)

    result = check_command(command, config)
    decision = result["decision"]
    reason = result["reason"]

    if decision == "block":
        try:
            log_blocked("Bash", command, reason, pattern=result.get("pattern"), rule_id=result.get("id"))
        except TypeError:
            log_blocked("Bash", command, reason)
        print(f"SECURITY: Blocked: {reason}", file=sys.stderr)
        print(f"Command: {command[:100]}{'...' if len(command) > 100 else ''}", file=sys.stderr)
        sys.exit(2)
    elif decision == "ask" and is_unattended():
        # No human present (scheduler dispatch). The interactive confirm is
        # meaningless, so fail closed: BLOCK + notify the owner, unless the
        # matched rule carries an unattended grant — and, when that grant is
        # path-scoped (#914), unless this command's target directory is inside
        # it. `hook_cwd` is the directory scope is measured from; see
        # `command_scope_dirs`.
        rule_id = result.get("id")
        hook_cwd = input_data.get("cwd") or os.environ.get("PWD") or os.getcwd()
        grants = resolve_unattended_grants(config)
        granted, why = unattended_grant_allows(
            rule_id, command, grants, hook_cwd, pattern=result.get("pattern"),
        )
        if granted:
            log_allowed("Bash", command, user_approved=False)
            sys.exit(0)
        try:
            log_blocked("Bash", command, f"unattended: {reason} — {why}",
                        pattern=result.get("pattern"), rule_id=rule_id)
        except TypeError:
            log_blocked("Bash", command, f"unattended: {reason} — {why}")
        _notify_unattended_block(command, f"{reason} — {why}", rule_id)
        print(f"SECURITY: Blocked (unattended — no human to confirm): {reason}", file=sys.stderr)
        print(f"Command: {command[:100]}{'...' if len(command) > 100 else ''}", file=sys.stderr)
        print(f"Why: {why}", file=sys.stderr)
        if rule_id and rule_id not in grants:
            print(f"To permit this for an unattended task, add rule id "
                  f"'{rule_id}' to its .agentwire.tasks.yml task `unattended_allow` "
                  f"(optionally scoped: `- {{id: {rule_id}, paths: [<dir>/]}}`).",
                  file=sys.stderr)
        sys.exit(2)
    elif decision == "ask" and permission_mode not in bypass_modes:
        log_asked("Bash", command, reason)
        output = {
            "hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "permissionDecision": "ask",
                "permissionDecisionReason": reason,
            }
        }
        print(json.dumps(output))
        sys.exit(0)
    elif result.get("escape"):
        log_escape("Bash", command, result.get("escape_reason") or "")
        sys.exit(0)
    elif result.get("disabled"):
        log_disabled("Bash", command)
        sys.exit(0)
    else:
        log_allowed("Bash", command, user_approved=False)
        sys.exit(0)


if __name__ == "__main__":
    main()
