#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.8"
# dependencies = ["pyyaml"]
# ///
"""
AgentWire Bash Tool Damage Control
==================================

Claude Code PreToolUse hook for Bash tool calls. Decides allow/block/ask based
on the merged rule set under ``agentwire/hooks/damage-control/rules/*.yaml``
(or the user's ``~/.agentwire/damage-control/*.yaml`` override) plus
ask-patterns generated from write-tier tooldef commands.

Implementation: the body of ``agentwire/safety/_core.py`` is inlined below
between the BEGIN/END GENERATED markers. Edit ``_core.py``, then run
``scripts/regen_damage_control_hooks.py`` — never edit between the markers.
"""

import json
import os
import sys
from pathlib import Path

# audit_logger lives next to this script
try:
    from audit_logger import log_allowed, log_asked, log_blocked, log_disabled, log_escape
except ImportError:
    def log_allowed(*args, **kwargs): pass
    def log_asked(*args, **kwargs): pass
    def log_blocked(*args, **kwargs): pass
    def log_disabled(*args, **kwargs): pass
    def log_escape(*args, **kwargs): pass


# === BEGIN GENERATED FROM agentwire/safety/_core.py ===
"""
Shared damage-control logic for both the agentwire CLI (`agentwire safety check`)
and the Claude Code PreToolUse hooks (bash/edit/write).

Single source of truth. The hook scripts inline this file's contents at the time
they're regenerated by ``scripts/regen_damage_control_hooks.py``; do not let this
file drift from what's inlined. ``tests/unit/test_damage_control_sync.py`` will
fail loudly if drift happens.
"""

import fnmatch
import os
import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

try:
    import yaml
except ImportError:
    yaml = None


# ============================================================================
# CONSTANTS
# ============================================================================

ALL_OPERATIONS = {"read", "write", "edit", "delete", "move", "chmod"}

# Operation pattern tuples: (regex template with {path} placeholder, operation name).

WRITE_PATTERNS = [
    (r'>\s*{path}', "write"),
    (r'\btee\s+(?!.*-a).*{path}', "write"),
    (r'\bdd\s+.*\bof=\S*{path}', "write"),
    (r'\brsync\s+.*\s+{path}', "write"),
    (r'\btar\s+(-c|--create)\S*\s+.*{path}', "write"),
    (r'\binstall\s+.*\s+{path}', "write"),
]

APPEND_PATTERNS = [
    (r'>>\s*{path}', "append"),
    (r'\btee\s+-a\s+.*{path}', "append"),
    (r'\btee\s+.*-a.*{path}', "append"),
]

EDIT_PATTERNS = [
    (r'\bsed\s+-i.*{path}', "edit"),
    (r'\bperl\s+-[^\s]*i.*{path}', "edit"),
    (r'\bawk\s+-i\s+inplace.*{path}', "edit"),
]

MOVE_COPY_PATTERNS = [
    (r'\bmv\s+.*\s+{path}', "move"),
    (r'\bcp\s+.*\s+{path}', "copy"),
]

DELETE_PATTERNS = [
    (r'\brm\s+.*{path}', "delete"),
    (r'\bunlink\s+.*{path}', "delete"),
    (r'\brmdir\s+.*{path}', "delete"),
    (r'\bshred\s+.*{path}', "delete"),
]

PERMISSION_PATTERNS = [
    (r'\bchmod\s+.*{path}', "chmod"),
    (r'\bchown\s+.*{path}', "chown"),
    (r'\bchgrp\s+.*{path}', "chgrp"),
]

TRUNCATE_PATTERNS = [
    (r'\btruncate\s+.*{path}', "truncate"),
    (r':\s*>\s*{path}', "truncate"),
]

READ_ONLY_BLOCKED = (
    WRITE_PATTERNS
    + APPEND_PATTERNS
    + EDIT_PATTERNS
    + MOVE_COPY_PATTERNS
    + DELETE_PATTERNS
    + PERMISSION_PATTERNS
    + TRUNCATE_PATTERNS
)

NO_DELETE_BLOCKED = DELETE_PATTERNS


# ============================================================================
# GLOB / PATH HELPERS
# ============================================================================


def is_glob_pattern(pattern: str) -> bool:
    return '*' in pattern or '?' in pattern or '[' in pattern


def glob_to_regex(pattern: str) -> str:
    """Convert a glob to a regex usable inside command-line contexts.

    Trailing word-boundary check ensures e.g. ``*.py`` doesn't match
    ``foo.python``.
    """
    result = ""
    for char in pattern:
        if char == '*':
            result += r'[^\s/]*'
        elif char == '?':
            result += r'[^\s/]'
        elif char in r'\.^$+{}[]|()':
            result += '\\' + char
        else:
            result += char
    result += r'(?![a-zA-Z0-9_])'
    return result


def matches_path_in_command(pattern: str, command: str) -> bool:
    """Check if a path pattern occurs in a command string in a path-context."""
    expanded = os.path.expanduser(pattern)
    if not is_glob_pattern(pattern):
        return expanded in command

    glob_regex = glob_to_regex(expanded)
    file_path_regex = r'(?:^|[\s/="\'<>])' + glob_regex + r'(?:[\s"\')<>]|$)'
    try:
        if not re.search(file_path_regex, command, re.IGNORECASE):
            return False
    except re.error:
        return False

    # Reject method-call lookalikes: foo.py( should not match *.py
    extension = pattern.split('*')[-1] if '*' in pattern else pattern
    if extension.startswith('.'):
        extension = extension[1:]
    if extension and re.search(r'\w\.' + re.escape(extension) + r'\s*\(', command):
        return False
    return True


def match_path(file_path: str, pattern: str) -> bool:
    """Match a single absolute file path against a pattern (glob or prefix)."""
    expanded_pattern = os.path.expanduser(pattern)
    normalized = os.path.normpath(file_path)
    expanded_normalized = os.path.expanduser(normalized)
    if is_glob_pattern(pattern):
        lower_path = expanded_normalized.lower()
        lower_pattern = expanded_pattern.lower()
        if fnmatch.fnmatch(lower_path, lower_pattern):
            return True
        basename = os.path.basename(expanded_normalized)
        if fnmatch.fnmatch(basename.lower(), lower_pattern):
            return True
        return False
    return (
        expanded_normalized.startswith(expanded_pattern)
        or expanded_normalized == expanded_pattern.rstrip('/')
    )


def _parse_allowed_entry(entry: Dict[str, Any]) -> Dict[str, Any]:
    """Normalize an allowed-paths entry to ``{path: str, allow: set}``."""
    allow = entry.get("allow", "all")
    if isinstance(allow, str) and allow.strip().lower() == "all":
        return {"path": entry["path"], "allow": ALL_OPERATIONS.copy()}
    if isinstance(allow, list):
        return {"path": entry["path"], "allow": {a.strip().lower() for a in allow}}
    if isinstance(allow, str):
        return {"path": entry["path"], "allow": {allow.strip().lower()}}
    return {"path": entry["path"], "allow": ALL_OPERATIONS.copy()}


def _find_project_config() -> Tuple[str, List[Any]]:
    """Walk up from $PWD to find ``.agentwire.yml`` and return its allowed_paths."""
    cwd = os.environ.get("PWD", os.getcwd())
    current = os.path.abspath(cwd)
    while True:
        config_file = os.path.join(current, ".agentwire.yml")
        if os.path.isfile(config_file):
            try:
                if yaml:
                    with open(config_file, "r") as f:
                        data = yaml.safe_load(f) or {}
                    safety = data.get("safety", {})
                    if isinstance(safety, dict):
                        paths = safety.get("allowed_paths", [])
                        if isinstance(paths, list):
                            return current, paths
            except Exception:
                pass
            return current, []
        parent = os.path.dirname(current)
        if parent == current:
            break
        current = parent
    return cwd, []


def load_allowed_paths(config: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Merge global ``allowedPaths`` from config with per-project ``.agentwire.yml`` entries."""
    raw = list(config.get("allowedPaths", []))

    project_root, project_paths = _find_project_config()
    for p in project_paths:
        if not isinstance(p, dict):
            continue
        entry = _parse_allowed_entry(p)
        if not os.path.isabs(os.path.expanduser(entry["path"])):
            entry["path"] = os.path.join(project_root, entry["path"])
        raw.append(entry)

    result = []
    for item in raw:
        if not isinstance(item, dict):
            continue
        if "allow" in item and isinstance(item["allow"], set):
            result.append(item)
        else:
            result.append(_parse_allowed_entry(item))
    return result


def is_path_allowed_for_op(
    file_path: str,
    allowed_paths: List[Dict[str, Any]],
    operation: str,
) -> bool:
    """Check if ``file_path`` has ``operation`` permitted by some allowed-path entry."""
    for entry in allowed_paths:
        if match_path(file_path, entry["path"]):
            if operation in entry["allow"]:
                return True
    return False


def _extract_command_paths(command: str) -> List[str]:
    """Extract file/directory paths from a bash command string."""
    paths = []
    for m in re.finditer(r'''["']([^"']+)["']''', command):
        candidate = m.group(1)
        if '/' in candidate or candidate.startswith('.'):
            paths.append(os.path.expanduser(candidate))
    for token in re.split(r'\s+', command):
        token = token.strip("\"'")
        if token.startswith(('/', '~/', './')):
            paths.append(os.path.expanduser(token))
        elif '/' in token and not token.startswith('-'):
            paths.append(os.path.expanduser(token))
    return paths


def is_command_path_allowed(
    command: str,
    allowed_paths: List[Dict[str, Any]],
    operation: str = "write",
) -> bool:
    """ALL paths in ``command`` must have ``operation`` permitted by allowlist.

    Security: ALL paths must match (not any) — this stops e.g.
    ``rm /tmp/safe.txt /etc/passwd`` from being allowed just because /tmp is
    allowlisted.
    """
    if not allowed_paths:
        return False
    paths = _extract_command_paths(command)
    if not paths:
        return False
    for p in paths:
        if not is_path_allowed_for_op(p, allowed_paths, operation):
            return False
    return True


def _infer_operation_from_reason(reason: str) -> str:
    """Map a pattern's reason text back to one of the allowlist operation names."""
    reason_lower = reason.lower()
    if (
        "rm" in reason_lower
        or "delet" in reason_lower
        or "trash" in reason_lower
        or "rmdir" in reason_lower
    ):
        return "delete"
    if "chmod" in reason_lower or "permission" in reason_lower:
        return "chmod"
    if "chown" in reason_lower or "chgrp" in reason_lower:
        return "chmod"
    if "mv" in reason_lower or "move" in reason_lower:
        return "move"
    return "write"


def check_path_patterns(
    command: str,
    path: str,
    patterns: List[Tuple[str, str]],
    path_type: str,
) -> Tuple[bool, str]:
    """Check if any operation pattern matches ``command`` targeting ``path``.

    Returns ``(matched, reason)`` where reason names the operation that triggered.
    """
    if is_glob_pattern(path):
        path_regex = glob_to_regex(path)
    else:
        expanded = os.path.expanduser(path)
        if expanded == path:
            path_regex = re.escape(path)
        else:
            path_regex = r'(?:' + re.escape(expanded) + r'|' + re.escape(path) + r')'

    for pattern_template, operation in patterns:
        try:
            full_pattern = pattern_template.replace("{path}", path_regex)
            if re.search(full_pattern, command, re.IGNORECASE):
                return True, f"{operation} operation on {path_type} {path}"
        except re.error:
            continue
    return False, ""


# ============================================================================
# CONFIG LOADING
# ============================================================================


def _cmd_to_regex(cmd: str) -> Optional[str]:
    """Convert a tooldef command string to a regex matching its fixed prefix.

    Stops at the first flag (- or --), placeholder (<...>), or optional ([...]).
    Example: ``gws gmail +send --to <addr>`` -> ``\\bgws\\s+gmail\\s+\\+send\\b``
    """
    tokens = cmd.strip().split()
    fixed = []
    for token in tokens:
        if token.startswith('<') or token.startswith('[') or token.startswith('-'):
            break
        fixed.append(token)
    if not fixed:
        return None
    parts = [re.escape(t) for t in fixed]
    pattern = r'\b' + r'\s+'.join(parts)
    last = fixed[-1]
    if last and (last[-1].isalnum() or last[-1] == '_'):
        pattern += r'\b'
    return pattern


def load_write_patterns_from_tooldefs(tooldefs_dir: Optional[Path]) -> List[Dict[str, Any]]:
    """Generate ``ask:true`` patterns from write-tier commands in tooldef YAMLs."""
    if not yaml:
        return []
    patterns: List[Dict[str, Any]] = []
    if not tooldefs_dir or not tooldefs_dir.exists():
        return patterns
    for tf_file in sorted(tooldefs_dir.glob("*.yaml")):
        try:
            with open(tf_file, "r") as f:
                data = yaml.safe_load(f) or {}
            tool_name = data.get("name", tf_file.stem)
            for cmd_def in data.get("commands", []):
                if cmd_def.get("access") != "write":
                    continue
                cmd_str = cmd_def.get("cmd", "")
                regex = _cmd_to_regex(cmd_str)
                if not regex:
                    continue
                patterns.append({
                    "pattern": regex,
                    "reason": f"{tool_name}: {cmd_def.get('description', cmd_str)}",
                    "ask": True,
                })
        except Exception:
            continue
    return patterns


_RULE_ID_SLUG_RE = re.compile(r"[^a-z0-9]+")


def _slug_for_rule(text: str, max_len: int = 60) -> str:
    """Lowercase, ASCII, kebab-case slug suitable for rule IDs."""
    s = _RULE_ID_SLUG_RE.sub("-", (text or "").lower()).strip("-")
    return s[:max_len] or "rule"


def _assign_rule_id(pattern_obj: Dict[str, Any], file_stem: str, taken: set) -> str:
    """Generate (or honor) an ID for a bash pattern. Mutates pattern_obj in place."""
    existing = pattern_obj.get("id")
    if isinstance(existing, str) and existing.strip():
        pattern_obj["id"] = existing.strip()
        taken.add(pattern_obj["id"])
        return pattern_obj["id"]
    slug = _slug_for_rule(pattern_obj.get("reason", "rule"))
    candidate = f"{file_stem}.{slug}"
    n = 2
    while candidate in taken:
        candidate = f"{file_stem}.{slug}-{n}"
        n += 1
    pattern_obj["id"] = candidate
    taken.add(candidate)
    return candidate


def load_config(
    rules_dir: Path,
    tooldefs_dir: Optional[Path] = None,
) -> Dict[str, Any]:
    """Load and merge all rule YAMLs in ``rules_dir`` plus tooldef ask-patterns.

    Bash patterns get a stable ``id`` field (``"<file>.<slug-of-reason>"``) so
    they can be referenced by the ``safety.disabled_rules`` config.
    """
    merged: Dict[str, Any] = {
        "bashToolPatterns": [],
        "zeroAccessPaths": [],
        "readOnlyPaths": [],
        "noDeletePaths": [],
        "allowedPaths": [],
    }
    if not yaml or not rules_dir.exists():
        return merged
    taken_ids: set = set()
    yaml_files = sorted(rules_dir.glob("*.yaml"))
    for rules_file in yaml_files:
        try:
            with open(rules_file, "r") as f:
                data = yaml.safe_load(f) or {}
            for key in merged:
                items = data.get(key, []) or []
                if key == "bashToolPatterns":
                    for it in items:
                        if isinstance(it, dict):
                            _assign_rule_id(it, rules_file.stem, taken_ids)
                            it.setdefault("source", rules_file.stem)
                merged[key].extend(items)
        except Exception:
            continue
    if tooldefs_dir is not None:
        tooldef_patterns = load_write_patterns_from_tooldefs(tooldefs_dir)
        for it in tooldef_patterns:
            _assign_rule_id(it, "tooldef", taken_ids)
            it.setdefault("source", "tooldef")
        merged["bashToolPatterns"].extend(tooldef_patterns)
    return merged


def load_safety_config(
    global_config_path: Optional[Path] = None,
    cwd: Optional[str] = None,
) -> Dict[str, Any]:
    """Resolve the effective ``safety`` block from global + nearest project config.

    Returns ``{enabled: bool, disabled_rules: list[str]}``. Project ``.agentwire.yml``
    overrides global; ``disabled_rules`` are merged (set-union).
    """
    enabled = True
    disabled_rules: List[str] = []
    project_enabled: Optional[bool] = None
    if not yaml:
        return {"enabled": enabled, "disabled_rules": disabled_rules}

    if global_config_path is None:
        global_config_path = Path.home() / ".agentwire" / "config.yaml"
    try:
        if global_config_path.exists():
            with open(global_config_path, "r") as f:
                data = yaml.safe_load(f) or {}
            safety = data.get("safety", {})
            if isinstance(safety, dict):
                if "enabled" in safety:
                    enabled = bool(safety["enabled"])
                rules = safety.get("disabled_rules", [])
                if isinstance(rules, list):
                    disabled_rules.extend(str(r) for r in rules if r)
    except Exception:
        pass

    if cwd is None:
        cwd = os.environ.get("PWD", os.getcwd())
    current = os.path.abspath(cwd)
    while True:
        candidate = os.path.join(current, ".agentwire.yml")
        if os.path.isfile(candidate):
            try:
                with open(candidate, "r") as f:
                    pdata = yaml.safe_load(f) or {}
                psafety = pdata.get("safety", {})
                if isinstance(psafety, dict):
                    if "enabled" in psafety and psafety["enabled"] is not None:
                        project_enabled = bool(psafety["enabled"])
                    prules = psafety.get("disabled_rules", [])
                    if isinstance(prules, list):
                        disabled_rules.extend(str(r) for r in prules if r)
            except Exception:
                pass
            break
        parent = os.path.dirname(current)
        if parent == current:
            break
        current = parent

    if project_enabled is not None:
        enabled = project_enabled

    return {"enabled": enabled, "disabled_rules": sorted(set(disabled_rules))}


_ESCAPE_HATCH_RE = re.compile(r"#\s*allow:[ \t]*([^\n]+)", re.IGNORECASE)


def detect_escape_hatch(command: str) -> Optional[str]:
    """Return the reason if ``command`` contains a ``# allow: <reason>`` marker.

    Non-empty reason required; matches the rest of the comment line so the
    marker works on multi-line / chained commands too.
    """
    if not command:
        return None
    m = _ESCAPE_HATCH_RE.search(command)
    if not m:
        return None
    reason = m.group(1).strip()
    return reason or None


# ============================================================================
# MISSION-WORKER RULES
# ============================================================================
#
# When a tmux session is a mission worker (its name is "{repo}/mission-{N}-{slug}",
# carried through to hooks as the ``AGENTWIRE_SESSION_NAME`` env var), tighten
# damage control beyond the standard ruleset:
#
#   1. Edit/Write must target a path inside a mission worktree
#      (``{...}-worktrees/mission-{N}-{slug}/...``). No writing to the canonical
#      repo, sibling projects, or arbitrary filesystem locations.
#   2. Bash ``git push --force`` (or ``--force-with-lease``) is blocked unless
#      the target is a mission-* branch and not main/master/develop.
#
# Detection uses the session-name regex (set by ``cmd_new`` / spawn lifecycle);
# enforcement uses a separate path regex to allow simple realpath checks.

_MISSION_SESSION_RE = re.compile(r"^[^/]+/mission-\d+-")
_MISSION_WORKTREE_PATH_RE = re.compile(r"-worktrees/mission-\d+-")
_PROTECTED_BRANCH_RE = re.compile(r"\b(?:main|master|develop)\b")
_FORCE_PUSH_RE = re.compile(r"\bgit\s+push\b[^|;&]*--force(?:-with-lease)?\b", re.IGNORECASE)


def _is_mission_worker_session() -> bool:
    """True iff ``AGENTWIRE_SESSION_NAME`` env var matches the mission pattern."""
    return bool(_MISSION_SESSION_RE.match(os.environ.get("AGENTWIRE_SESSION_NAME", "") or ""))


def check_mission_worker_path(file_path: str) -> Tuple[bool, str]:
    """If we're in a mission worker, allow only paths under a mission worktree.

    Returns ``(blocked, reason)``. ``(False, "")`` when not in a mission session
    or when ``file_path`` resolves inside a ``*-worktrees/mission-N-...`` dir.

    Realpath is used so symlink escapes from within the worktree still resolve
    to their canonical location for the check.
    """
    if not _is_mission_worker_session():
        return False, ""
    try:
        abs_path = os.path.realpath(os.path.expanduser(file_path))
    except (OSError, ValueError):
        return False, ""
    if _MISSION_WORKTREE_PATH_RE.search(abs_path):
        return False, ""
    return True, (
        "mission worker may only write inside its assigned worktree "
        "({repo}-worktrees/mission-{N}-{slug}/...)"
    )


def check_mission_worker_bash(command: str) -> Tuple[bool, str]:
    """If we're in a mission worker, gate force-pushes by target branch.

    Rules:
      - Any ``git push --force`` referencing ``main`` / ``master`` / ``develop``
        is blocked outright.
      - A ``git push --force`` targeting a ``mission-*`` branch is allowed
        (the worker's own branch; rebases on top of merge-base happen here).
      - All other ``git push --force`` patterns are blocked — mission workers
        should never overwrite shared history.

    Returns ``(blocked, reason)``; ``(False, "")`` if not in a mission session
    or the command isn't a force-push.
    """
    if not _is_mission_worker_session():
        return False, ""
    if not _FORCE_PUSH_RE.search(command):
        return False, ""
    if _PROTECTED_BRANCH_RE.search(command):
        return True, "mission worker: --force push to main/master/develop is blocked"
    if re.search(r"\bmission-\d+-", command):
        return False, ""
    return True, "mission worker: --force push allowed only on mission-* branches"


# ============================================================================
# DECISION LADDERS
# ============================================================================


def check_command(command: str, config: Dict[str, Any]) -> Dict[str, Any]:
    """Decide whether a bash command should be allowed/blocked/asked.

    Returns ``{decision, reason, pattern, command}`` plus optional ``id``,
    ``escape_reason``, ``escape``, ``disabled``.

    Order:
      0. Escape hatch (``# allow: <reason>``) → ALLOW (escape=True)
      1. Kill switch (``config["safety"]["enabled"] is False``) → ALLOW (disabled=True)
      2. Hard-blocked bash patterns (skip if ``id`` in ``disabled_rules``)
      3. Ask patterns
      4. Bypassable bash patterns → check allowlist for required operation
      5. zeroAccessPaths → check allowlist with ``read`` permission
      6. readOnlyPaths → match against READ_ONLY_BLOCKED operation patterns
      7. noDeletePaths → match against NO_DELETE_BLOCKED patterns
    """
    safety_cfg = config.get("safety", {}) if isinstance(config.get("safety"), dict) else {}
    disabled_rules = set(safety_cfg.get("disabled_rules", []) or [])
    is_enabled = safety_cfg.get("enabled", True)

    escape_reason = detect_escape_hatch(command)
    if escape_reason:
        return {
            "decision": "allow",
            "reason": f"Escape hatch: {escape_reason}",
            "pattern": None,
            "command": command,
            "escape": True,
            "escape_reason": escape_reason,
        }

    if is_enabled is False:
        return {
            "decision": "allow",
            "reason": "safety disabled",
            "pattern": None,
            "command": command,
            "disabled": True,
        }

    blocked, reason = check_mission_worker_bash(command)
    if blocked:
        return {
            "decision": "block",
            "reason": reason,
            "pattern": "mission-worker:force-push",
            "command": command,
        }

    bash_patterns = config.get("bashToolPatterns", [])
    zero_access = config.get("zeroAccessPaths", [])
    read_only = config.get("readOnlyPaths", [])
    no_delete = config.get("noDeletePaths", [])
    allowed = load_allowed_paths(config)

    bypassable_matches: List[Tuple[str, str, Optional[str]]] = []

    for pattern_obj in bash_patterns:
        if not isinstance(pattern_obj, dict):
            continue
        rule_id = pattern_obj.get("id")
        if rule_id and rule_id in disabled_rules:
            continue
        pattern = pattern_obj.get("pattern", "")
        reason = pattern_obj.get("reason", "Matched pattern")
        should_ask = pattern_obj.get("ask", False)
        bypassable = pattern_obj.get("bypassable", False)
        try:
            if re.search(pattern, command, re.IGNORECASE):
                if should_ask:
                    return {
                        "decision": "ask",
                        "reason": reason,
                        "pattern": pattern,
                        "command": command,
                        "id": rule_id,
                    }
                elif bypassable:
                    bypassable_matches.append((pattern, reason, rule_id))
                else:
                    return {
                        "decision": "block",
                        "reason": reason,
                        "pattern": pattern,
                        "command": command,
                        "id": rule_id,
                    }
        except re.error:
            continue

    for pattern, reason, rule_id in bypassable_matches:
        operation = _infer_operation_from_reason(reason)
        if not is_command_path_allowed(command, allowed, operation):
            return {
                "decision": "block",
                "reason": reason,
                "pattern": pattern,
                "command": command,
                "id": rule_id,
            }

    for path in zero_access:
        if matches_path_in_command(path, command):
            if is_command_path_allowed(command, allowed, "read"):
                continue
            return {
                "decision": "block",
                "reason": f"Zero-access path: {path}",
                "pattern": f"zeroAccessPath: {path}",
                "command": command,
            }

    for path in read_only:
        matched, reason = check_path_patterns(command, path, READ_ONLY_BLOCKED, "read-only path")
        if matched:
            op = _infer_operation_from_reason(reason)
            if is_command_path_allowed(command, allowed, op):
                continue
            return {
                "decision": "block",
                "reason": f"Read-only path: {path}",
                "pattern": f"readOnlyPath: {path}",
                "command": command,
            }

    for path in no_delete:
        matched, _reason = check_path_patterns(command, path, NO_DELETE_BLOCKED, "no-delete path")
        if matched:
            if is_command_path_allowed(command, allowed, "delete"):
                continue
            return {
                "decision": "block",
                "reason": f"No-delete path: {path}",
                "pattern": f"noDeletePath: {path}",
                "command": command,
            }

    return {
        "decision": "allow",
        "reason": "No patterns matched",
        "pattern": None,
        "command": command,
    }


def check_path(file_path: str, config: Dict[str, Any]) -> Tuple[bool, str]:
    """File-path-only check used by edit/write hooks. Returns ``(blocked, reason)``."""
    safety_cfg = config.get("safety", {}) if isinstance(config.get("safety"), dict) else {}
    if safety_cfg.get("enabled", True) is False:
        return False, ""

    blocked, reason = check_mission_worker_path(file_path)
    if blocked:
        return True, reason

    allowed = load_allowed_paths(config)

    if is_path_allowed_for_op(file_path, allowed, "edit"):
        return False, ""

    for zero_path in config.get("zeroAccessPaths", []):
        if match_path(file_path, zero_path):
            return True, f"zero-access path {zero_path} (no operations allowed)"

    for readonly in config.get("readOnlyPaths", []):
        if match_path(file_path, readonly):
            return True, f"read-only path {readonly}"

    return False, ""
# === END GENERATED ===


# ============================================================================
# HOOK ENTRY POINT
# ============================================================================


def _resolve_rules_dir() -> Path:
    """User override (~/.agentwire/damage-control/) wins; else bundled rules/."""
    user_dir = Path(os.environ.get("AGENTWIRE_DIR", os.path.expanduser("~/.agentwire")))
    user_rules = user_dir / "damage-control"
    if user_rules.exists() and any(user_rules.glob("*.yaml")):
        return user_rules
    return Path(__file__).parent / "rules"


def _resolve_tooldefs_dir():
    """User tooldefs (~/.agentwire/tooldefs/) win; else bundled."""
    user_dir = Path(os.environ.get("AGENTWIRE_DIR", os.path.expanduser("~/.agentwire")))
    user_tooldefs = user_dir / "tooldefs"
    if user_tooldefs.exists() and any(user_tooldefs.glob("*.yaml")):
        return user_tooldefs
    bundled = Path(__file__).parent.parent.parent / "tooldefs"
    return bundled if bundled.exists() else None


def main() -> None:
    config = load_config(_resolve_rules_dir(), _resolve_tooldefs_dir())
    config["safety"] = load_safety_config()

    try:
        input_data = json.load(sys.stdin)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON input: {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error reading input: {e}", file=sys.stderr)
        sys.exit(1)

    tool_name = input_data.get("tool_name", "")
    tool_input = input_data.get("tool_input", {})
    # Claude Code passes ``permission_mode`` in the hook input. Two modes
    # indicate the user has explicitly opted out of ask-escalation friction:
    #   - "bypassPermissions" → --dangerously-skip-permissions
    #   - "auto"              → autonomous /loop or similar auto mode
    # Hard blocks still fire either way; ``ask:true`` patterns become allow.
    permission_mode = input_data.get("permission_mode", "")
    bypass_modes = {"bypassPermissions", "auto"}

    if tool_name != "Bash":
        sys.exit(0)

    command = tool_input.get("command", "")
    if not command:
        sys.exit(0)

    result = check_command(command, config)
    decision = result["decision"]
    reason = result["reason"]

    if decision == "block":
        try:
            log_blocked("Bash", command, reason, pattern=result.get("pattern"), rule_id=result.get("id"))
        except TypeError:
            log_blocked("Bash", command, reason)
        print(f"SECURITY: Blocked: {reason}", file=sys.stderr)
        print(f"Command: {command[:100]}{'...' if len(command) > 100 else ''}", file=sys.stderr)
        sys.exit(2)
    elif decision == "ask" and permission_mode not in bypass_modes:
        log_asked("Bash", command, reason)
        output = {
            "hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "permissionDecision": "ask",
                "permissionDecisionReason": reason,
            }
        }
        print(json.dumps(output))
        sys.exit(0)
    elif result.get("escape"):
        log_escape("Bash", command, result.get("escape_reason") or "")
        sys.exit(0)
    elif result.get("disabled"):
        log_disabled("Bash", command)
        sys.exit(0)
    else:
        log_allowed("Bash", command, user_approved=False)
        sys.exit(0)


if __name__ == "__main__":
    main()
