#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.8"
# dependencies = ["pyyaml"]
# ///
"""
AgentWire Write Tool Damage Control
===================================

Claude Code PreToolUse hook for Write tool calls. Blocks writes to protected
files using the same shared rule set as the Bash and Edit hooks.

Implementation: the body of ``agentwire/safety/_core.py`` is inlined below
between the BEGIN/END GENERATED markers. Edit ``_core.py``, then run
``scripts/regen_damage_control_hooks.py`` — never edit between the markers.
"""

import json
import os
import sys
from pathlib import Path

try:
    from audit_logger import log_allowed, log_blocked, log_disabled
except ImportError:
    def log_allowed(*args, **kwargs): pass
    def log_blocked(*args, **kwargs): pass
    def log_disabled(*args, **kwargs): pass


# === BEGIN GENERATED FROM agentwire/safety/_core.py ===
"""
Shared damage-control logic for both the agentwire CLI (`agentwire safety check`)
and the Claude Code PreToolUse hooks (bash/edit/write).

Single source of truth. The hook scripts inline this file's contents at the time
they're regenerated by ``scripts/regen_damage_control_hooks.py``; do not let this
file drift from what's inlined. ``tests/unit/test_damage_control_sync.py`` will
fail loudly if drift happens.
"""

import fnmatch
import os
import re
import shlex
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

try:
    import yaml
except ImportError:
    yaml = None


# ============================================================================
# CONSTANTS
# ============================================================================

ALL_OPERATIONS = {"read", "write", "edit", "delete", "move", "chmod"}

# Operation pattern tuples: (regex template with {path} placeholder, operation name).

WRITE_PATTERNS = [
    (r'>\s*{path}', "write"),
    (r'\btee\s+(?!.*-a).*{path}', "write"),
    (r'\bdd\s+.*\bof=\S*{path}', "write"),
    (r'\brsync\s+.*\s+{path}', "write"),
    (r'\btar\s+(-c|--create)\S*\s+.*{path}', "write"),
    (r'\binstall\s+.*\s+{path}', "write"),
]

APPEND_PATTERNS = [
    (r'>>\s*{path}', "append"),
    (r'\btee\s+-a\s+.*{path}', "append"),
    (r'\btee\s+.*-a.*{path}', "append"),
]

EDIT_PATTERNS = [
    (r'\bsed\s+-i.*{path}', "edit"),
    (r'\bperl\s+-[^\s]*i.*{path}', "edit"),
    (r'\bawk\s+-i\s+inplace.*{path}', "edit"),
]

MOVE_COPY_PATTERNS = [
    (r'\bmv\s+.*\s+{path}', "move"),
    (r'\bcp\s+.*\s+{path}', "copy"),
]

DELETE_PATTERNS = [
    (r'\brm\s+.*{path}', "delete"),
    (r'\bunlink\s+.*{path}', "delete"),
    (r'\brmdir\s+.*{path}', "delete"),
    (r'\bshred\s+.*{path}', "delete"),
]

PERMISSION_PATTERNS = [
    (r'\bchmod\s+.*{path}', "chmod"),
    (r'\bchown\s+.*{path}', "chown"),
    (r'\bchgrp\s+.*{path}', "chgrp"),
]

TRUNCATE_PATTERNS = [
    (r'\btruncate\s+.*{path}', "truncate"),
    (r':\s*>\s*{path}', "truncate"),
]

READ_ONLY_BLOCKED = (
    WRITE_PATTERNS
    + APPEND_PATTERNS
    + EDIT_PATTERNS
    + MOVE_COPY_PATTERNS
    + DELETE_PATTERNS
    + PERMISSION_PATTERNS
    + TRUNCATE_PATTERNS
)

NO_DELETE_BLOCKED = DELETE_PATTERNS


# ============================================================================
# GLOB / PATH HELPERS
# ============================================================================


def is_glob_pattern(pattern: str) -> bool:
    return '*' in pattern or '?' in pattern or '[' in pattern


def glob_to_regex(pattern: str) -> str:
    """Convert a glob to a regex usable inside command-line contexts.

    Trailing word-boundary check ensures e.g. ``*.py`` doesn't match
    ``foo.python``.
    """
    result = ""
    for char in pattern:
        if char == '*':
            result += r'[^\s/]*'
        elif char == '?':
            result += r'[^\s/]'
        elif char in r'\.^$+{}[]|()':
            result += '\\' + char
        else:
            result += char
    result += r'(?![a-zA-Z0-9_])'
    return result


def canonicalize_command(command: str) -> str:
    """Expand ``~``, ``$HOME`` and ``${HOME}`` in a command to the home dir.

    The rule patterns are stored in ``~``-form and expanded with
    ``expanduser`` before matching; without expanding the COMMAND too, a
    tilde/``$HOME`` secret read (``cat ~/.ssh/id_rsa``, ``cat $HOME/.aws/credentials``)
    only ever matched against its fully-expanded ``/Users/<me>/...`` form and
    slipped past. Canonicalizing both sides closes that gap. ``./``-prefixes are
    handled by the path-context boundary in :func:`path_match_regex` (a leading
    ``/`` is an accepted boundary char), so no separate ``normpath`` of the raw
    command string — which is not a pure path — is attempted here.
    """
    home = os.path.expanduser("~")
    if not home or home == "~":
        return command
    out = command.replace("${HOME}", home).replace("$HOME", home)
    # Only expand ``~`` when it begins a path (start of string or after a
    # whitespace/quote/=/: boundary and immediately followed by ``/``), so we
    # never touch ``~`` used as a literal (e.g. inside a sed expression).
    out = re.sub(r'(^|[\s=:"\'(<>])~(?=/)', lambda m: m.group(1) + home, out)
    return out


def path_match_regex(expanded_pattern: str) -> str:
    """Build a path-context regex for a rule pattern (glob or literal).

    Both glob and literal patterns are matched as a whole path COMPONENT — never
    a bare substring. The literal branch previously used ``expanded in command``,
    which hard-blocked innocuous text: ``.env`` matched ``.environment``,
    ``docs/.env.example``, ``grep -v .environ`` (#492). The component boundary
    (a leading path-separator/whitespace boundary, and a trailing boundary that
    forbids the basename being extended by another filename char) fixes those
    false positives while still catching real secret paths.
    """
    lead = r'(?:^|[\s=:"\'<>(/])'
    if is_glob_pattern(expanded_pattern):
        glob_regex = glob_to_regex(expanded_pattern)
        return r'(?:^|[\s/="\'<>])' + glob_regex + r'(?:[\s"\')<>]|$)'
    is_dir = expanded_pattern.endswith('/')
    body = re.escape(expanded_pattern.rstrip('/'))
    if is_dir:
        # Directory prefix: anything under it counts as a hit.
        trail = r'(?:/|[\s"\')<>;&|]|$)'
    else:
        # Filename/path: the basename must end here — the next char must not be
        # a path-extending char, so ``.env`` no longer matches ``.env.example``.
        trail = r'(?![A-Za-z0-9_.\-])'
    return lead + body + trail


# ``.env.example`` / ``.env.sample`` / ``.env.template`` / ``.env.dist`` are
# committed, secret-free TEMPLATE files — never the real env. The ``.env.*`` glob
# would otherwise hard-block reading them (#492), so they are carved out.
_SAFE_ENV_TEMPLATE_RE = re.compile(
    r'\.env\.(?:example|sample|template|dist)(?![A-Za-z0-9_])', re.IGNORECASE
)


def matches_path_in_command(pattern: str, command: str) -> bool:
    """Check if a path pattern occurs in a command string in a path-context.

    The command is canonicalized (``~``/``$HOME`` expanded) and the pattern is
    matched as a whole path component against both the raw and canonicalized
    forms, so neither tilde indirection (#2) nor bare-substring over-blocking
    (#492) defeats it.
    """
    expanded = os.path.expanduser(pattern)
    regex = path_match_regex(expanded)
    haystacks = [command]
    canon = canonicalize_command(command)
    if canon != command:
        haystacks.append(canon)

    matched = False
    for hay in haystacks:
        try:
            m = re.search(regex, hay, re.IGNORECASE)
        except re.error:
            return False
        if m and not _SAFE_ENV_TEMPLATE_RE.search(m.group(0)):
            matched = True
            break
    if not matched:
        return False

    if is_glob_pattern(pattern):
        # Reject method-call lookalikes: foo.py( should not match *.py
        extension = pattern.split('*')[-1] if '*' in pattern else pattern
        if extension.startswith('.'):
            extension = extension[1:]
        if extension and re.search(r'\w\.' + re.escape(extension) + r'\s*\(', command):
            return False
    return True


def match_path(file_path: str, pattern: str) -> bool:
    """Match a single absolute file path against a pattern (glob or prefix)."""
    expanded_pattern = os.path.expanduser(pattern)
    normalized = os.path.normpath(file_path)
    expanded_normalized = os.path.expanduser(normalized)
    if is_glob_pattern(pattern):
        lower_path = expanded_normalized.lower()
        lower_pattern = expanded_pattern.lower()
        if fnmatch.fnmatch(lower_path, lower_pattern):
            return True
        basename = os.path.basename(expanded_normalized)
        if fnmatch.fnmatch(basename.lower(), lower_pattern):
            return True
        return False
    return (
        expanded_normalized.startswith(expanded_pattern)
        or expanded_normalized == expanded_pattern.rstrip('/')
    )


def _parse_allowed_entry(entry: Dict[str, Any]) -> Dict[str, Any]:
    """Normalize an allowed-paths entry to ``{path: str, allow: set}``."""
    allow = entry.get("allow", "all")
    if isinstance(allow, str) and allow.strip().lower() == "all":
        return {"path": entry["path"], "allow": ALL_OPERATIONS.copy()}
    if isinstance(allow, list):
        return {"path": entry["path"], "allow": {a.strip().lower() for a in allow}}
    if isinstance(allow, str):
        return {"path": entry["path"], "allow": {allow.strip().lower()}}
    return {"path": entry["path"], "allow": ALL_OPERATIONS.copy()}


def _find_project_config() -> Tuple[str, List[Any]]:
    """Walk up from $PWD to find ``.damagecontrol.yml`` and return its allowed_paths.

    The per-project allowlist lives in the PROTECTED ``.damagecontrol.yml``
    (top-level ``allowed_paths``), never the agent-writable ``.agentwire.yml``.
    Otherwise an agent could allowlist a control-plane path in ``.agentwire.yml``
    and re-permit its own write to ``damagecontrol.yml`` — the exact bypass #466
    set out to close. The allowlist is the one knob that overrides the protected
    check, so it must itself live behind the protected control plane (#467).
    """
    cwd = os.environ.get("PWD", os.getcwd())
    current = os.path.abspath(cwd)
    while True:
        config_file = os.path.join(current, ".damagecontrol.yml")
        if os.path.isfile(config_file):
            try:
                if yaml:
                    with open(config_file, "r") as f:
                        data = yaml.safe_load(f) or {}
                    if isinstance(data, dict):
                        paths = data.get("allowed_paths", [])
                        if isinstance(paths, list):
                            return current, paths
            except Exception:
                pass
            return current, []
        parent = os.path.dirname(current)
        if parent == current:
            break
        current = parent
    return cwd, []


def load_allowed_paths(config: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Merge global ``allowedPaths`` from config with per-project ``.damagecontrol.yml`` entries."""
    raw = list(config.get("allowedPaths", []))

    project_root, project_paths = _find_project_config()
    for p in project_paths:
        if not isinstance(p, dict):
            continue
        entry = _parse_allowed_entry(p)
        if not os.path.isabs(os.path.expanduser(entry["path"])):
            entry["path"] = os.path.join(project_root, entry["path"])
        raw.append(entry)

    result = []
    for item in raw:
        if not isinstance(item, dict):
            continue
        if "allow" in item and isinstance(item["allow"], set):
            result.append(item)
        else:
            result.append(_parse_allowed_entry(item))
    return result


def is_path_allowed_for_op(
    file_path: str,
    allowed_paths: List[Dict[str, Any]],
    operation: str,
) -> bool:
    """Check if ``file_path`` has ``operation`` permitted by some allowed-path entry."""
    for entry in allowed_paths:
        if match_path(file_path, entry["path"]):
            if operation in entry["allow"]:
                return True
    return False


def _extract_command_paths(command: str) -> List[str]:
    """Extract file/directory paths from a bash command string."""
    paths = []
    for m in re.finditer(r'''["']([^"']+)["']''', command):
        candidate = m.group(1)
        if '/' in candidate or candidate.startswith('.'):
            paths.append(os.path.expanduser(candidate))
    for token in re.split(r'\s+', command):
        token = token.strip("\"'")
        if token.startswith(('/', '~/', './')):
            paths.append(os.path.expanduser(token))
        elif '/' in token and not token.startswith('-'):
            paths.append(os.path.expanduser(token))
    return paths


def is_command_path_allowed(
    command: str,
    allowed_paths: List[Dict[str, Any]],
    operation: str = "write",
) -> bool:
    """ALL paths in ``command`` must have ``operation`` permitted by allowlist.

    Security: ALL paths must match (not any) — this stops e.g.
    ``rm /tmp/safe.txt /etc/passwd`` from being allowed just because /tmp is
    allowlisted.
    """
    if not allowed_paths:
        return False
    paths = _extract_command_paths(command)
    if not paths:
        return False
    for p in paths:
        if not is_path_allowed_for_op(p, allowed_paths, operation):
            return False
    return True


def _infer_operation_from_reason(reason: str) -> str:
    """Map a pattern's reason text back to one of the allowlist operation names."""
    reason_lower = reason.lower()
    if (
        "rm" in reason_lower
        or "delet" in reason_lower
        or "trash" in reason_lower
        or "rmdir" in reason_lower
    ):
        return "delete"
    if "chmod" in reason_lower or "permission" in reason_lower:
        return "chmod"
    if "chown" in reason_lower or "chgrp" in reason_lower:
        return "chmod"
    if "mv" in reason_lower or "move" in reason_lower:
        return "move"
    return "write"


def check_path_patterns(
    command: str,
    path: str,
    patterns: List[Tuple[str, str]],
    path_type: str,
) -> Tuple[bool, str]:
    """Check if any operation pattern matches ``command`` targeting ``path``.

    Returns ``(matched, reason)`` where reason names the operation that triggered.
    """
    if is_glob_pattern(path):
        path_regex = glob_to_regex(path)
    else:
        expanded = os.path.expanduser(path)
        if expanded == path:
            path_regex = re.escape(path)
        else:
            path_regex = r'(?:' + re.escape(expanded) + r'|' + re.escape(path) + r')'

    for pattern_template, operation in patterns:
        try:
            full_pattern = pattern_template.replace("{path}", path_regex)
            if re.search(full_pattern, command, re.IGNORECASE):
                return True, f"{operation} operation on {path_type} {path}"
        except re.error:
            continue
    return False, ""


# ============================================================================
# CONFIG LOADING
# ============================================================================


def _cmd_to_regex(cmd: str) -> Optional[str]:
    """Convert a tooldef command string to a regex matching its fixed prefix.

    Stops at the first flag (- or --), placeholder (<...>), or optional ([...]).
    Example: ``gws gmail +send --to <addr>`` -> ``\\bgws\\s+gmail\\s+\\+send\\b``
    """
    tokens = cmd.strip().split()
    fixed = []
    for token in tokens:
        if token.startswith('<') or token.startswith('[') or token.startswith('-'):
            break
        fixed.append(token)
    if not fixed:
        return None
    parts = [re.escape(t) for t in fixed]
    pattern = r'\b' + r'\s+'.join(parts)
    last = fixed[-1]
    if last and (last[-1].isalnum() or last[-1] == '_'):
        pattern += r'\b'
    return pattern


def load_write_patterns_from_tooldefs(tooldefs_dir: Optional[Path]) -> List[Dict[str, Any]]:
    """Generate ``ask:true`` patterns from write-tier commands in tooldef YAMLs."""
    if not yaml:
        return []
    patterns: List[Dict[str, Any]] = []
    if not tooldefs_dir or not tooldefs_dir.exists():
        return patterns
    for tf_file in sorted(tooldefs_dir.glob("*.yaml")):
        try:
            with open(tf_file, "r") as f:
                data = yaml.safe_load(f) or {}
            tool_name = data.get("name", tf_file.stem)
            for cmd_def in data.get("commands", []):
                if cmd_def.get("access") != "write":
                    continue
                cmd_str = cmd_def.get("cmd", "")
                regex = _cmd_to_regex(cmd_str)
                if not regex:
                    continue
                entry = {
                    "pattern": regex,
                    "reason": f"{tool_name}: {cmd_def.get('description', cmd_str)}",
                    "ask": True,
                }
                # An explicit ``id:`` on the tooldef command yields a stable
                # rule ID (e.g. ``git.push``) that survives description edits —
                # needed so ``safety.unattended_allow`` can name it reliably.
                # Without one, ``_assign_rule_id`` derives a slug from the reason.
                if cmd_def.get("id"):
                    entry["id"] = str(cmd_def["id"])
                patterns.append(entry)
        except Exception:
            continue
    return patterns


_RULE_ID_SLUG_RE = re.compile(r"[^a-z0-9]+")


def _slug_for_rule(text: str, max_len: int = 60) -> str:
    """Lowercase, ASCII, kebab-case slug suitable for rule IDs."""
    s = _RULE_ID_SLUG_RE.sub("-", (text or "").lower()).strip("-")
    return s[:max_len] or "rule"


def _assign_rule_id(pattern_obj: Dict[str, Any], file_stem: str, taken: set) -> str:
    """Generate (or honor) an ID for a bash pattern. Mutates pattern_obj in place."""
    existing = pattern_obj.get("id")
    if isinstance(existing, str) and existing.strip():
        pattern_obj["id"] = existing.strip()
        taken.add(pattern_obj["id"])
        return pattern_obj["id"]
    slug = _slug_for_rule(pattern_obj.get("reason", "rule"))
    candidate = f"{file_stem}.{slug}"
    n = 2
    while candidate in taken:
        candidate = f"{file_stem}.{slug}-{n}"
        n += 1
    pattern_obj["id"] = candidate
    taken.add(candidate)
    return candidate


def load_config(
    rules_dir: Path,
    tooldefs_dir: Optional[Path] = None,
) -> Dict[str, Any]:
    """Load and merge all rule YAMLs in ``rules_dir`` plus tooldef ask-patterns.

    Bash patterns get a stable ``id`` field (``"<file>.<slug-of-reason>"``) so
    they can be referenced by the ``safety.disabled_rules`` config.
    """
    merged: Dict[str, Any] = {
        "bashToolPatterns": [],
        "zeroAccessPaths": [],
        "readOnlyPaths": [],
        "noDeletePaths": [],
        "allowedPaths": [],
    }
    if not yaml:
        # No YAML parser ⇒ we cannot load ANY rules. Returning the empty rule set
        # would silently disable all protection (fail OPEN). Mark the config so
        # the decision ladder fails CLOSED instead.
        merged["_parser_unavailable"] = "pyyaml unavailable — cannot load rules"
        return merged
    if not rules_dir.exists():
        return merged
    taken_ids: set = set()
    yaml_files = sorted(rules_dir.glob("*.yaml"))
    for rules_file in yaml_files:
        try:
            with open(rules_file, "r") as f:
                data = yaml.safe_load(f) or {}
            for key in merged:
                items = data.get(key, []) or []
                if key == "bashToolPatterns":
                    for it in items:
                        if isinstance(it, dict):
                            _assign_rule_id(it, rules_file.stem, taken_ids)
                            it.setdefault("source", rules_file.stem)
                merged[key].extend(items)
        except Exception:
            continue
    if tooldefs_dir is not None:
        tooldef_patterns = load_write_patterns_from_tooldefs(tooldefs_dir)
        for it in tooldef_patterns:
            _assign_rule_id(it, "tooldef", taken_ids)
            it.setdefault("source", "tooldef")
        merged["bashToolPatterns"].extend(tooldef_patterns)
    return merged


# ============================================================================
# UNATTENDED (NO-HUMAN-PRESENT) RESOLUTION
# ============================================================================
#
# The damage-control hook classifies commands into allow / block / ask. The
# ``ask`` tier only means something when a human is present to confirm. Under
# the scheduler (cron, nobody watching) sessions run with
# ``--dangerously-skip-permissions``, so historically ``ask`` resolved to a
# SILENT allow — an unsupervised agent could deploy / drop a table / force-push.
#
# When a session is marked unattended (``AGENTWIRE_UNATTENDED=1``, stamped at
# dispatch by the scheduler), the hook resolves ``ask`` by FAILING CLOSED:
# block + notify the owner, UNLESS the matched rule's stable ID is on the
# allowlist. The allowlist is the union of:
#   1. ``DEFAULT_UNATTENDED_ALLOW`` below (tight — work + open a PR, nothing
#      irreversible or outward-facing),
#   2. ``safety.unattended_allow`` from global / project config,
#   3. ``AGENTWIRE_UNATTENDED_ALLOW`` (comma-separated) — the per-task
#      extension the scheduler stamps from a task's ``unattended_allow``.
#
# Hard ``block`` rules (rm -rf, git push --force, …) are unaffected — they fire
# regardless. Interactive bypass sessions (no ``AGENTWIRE_UNATTENDED``) are
# unaffected too — their ``ask`` still resolves the old way.

DEFAULT_UNATTENDED_ALLOW = {
    "git.add",       # stage files
    "git.add-u",     # stage tracked changes
    "git.commit",    # commit
    "git.push",      # push (force/delete are SEPARATE hard-block/ask rules)
    "gh.pr-create",  # open a PR — the human-reviewed gate
}


def is_unattended() -> bool:
    """True when this session was dispatched with no human present (scheduler)."""
    return os.environ.get("AGENTWIRE_UNATTENDED") == "1"


def resolve_unattended_allow(config: Dict[str, Any]) -> set:
    """Effective unattended allowlist: defaults ∪ config ∪ per-task env extension."""
    allow = set(DEFAULT_UNATTENDED_ALLOW)
    safety_cfg = config.get("safety", {}) if isinstance(config.get("safety"), dict) else {}
    for rid in safety_cfg.get("unattended_allow", []) or []:
        if rid:
            allow.add(str(rid))
    env_allow = os.environ.get("AGENTWIRE_UNATTENDED_ALLOW", "")
    for rid in env_allow.split(","):
        rid = rid.strip()
        if rid:
            allow.add(rid)
    return allow


def load_safety_config(
    global_config_path: Optional[Path] = None,
    cwd: Optional[str] = None,
) -> Dict[str, Any]:
    """Resolve the effective safety knobs from the dedicated damage-control files.

    The kill switch and rule knobs live in HOST-OWNED, agent-unwritable files
    (see ``is_protected_control_plane``) — never in ``config.yaml`` /
    ``.agentwire.yml``, which the policed agent can edit:

      * Global:  ``~/.agentwire/damagecontrol.yml``
      * Project: ``.damagecontrol.yml`` (nearest, walking up from ``cwd``)

    Each holds top-level ``enabled`` / ``disabled_rules`` / ``unattended_allow``.
    Returns ``{enabled, disabled_rules, unattended_allow}``. A project
    ``.damagecontrol.yml`` may both loosen AND tighten ``enabled`` (it simply
    wins); ``disabled_rules`` / ``unattended_allow`` are merged (set-union).

    Fail-secure: a missing/unreadable/yaml-less global file ⇒ ``enabled: true``.
    """
    enabled = True
    disabled_rules: List[str] = []
    unattended_allow: List[str] = []
    project_enabled: Optional[bool] = None
    if not yaml:
        return {"enabled": enabled, "disabled_rules": disabled_rules,
                "unattended_allow": unattended_allow}

    def _absorb(data: Any) -> Optional[bool]:
        """Pull knobs from a parsed policy doc; return its ``enabled`` (or None)."""
        local_enabled: Optional[bool] = None
        if isinstance(data, dict):
            if "enabled" in data and data["enabled"] is not None:
                local_enabled = bool(data["enabled"])
            rules = data.get("disabled_rules", [])
            if isinstance(rules, list):
                disabled_rules.extend(str(r) for r in rules if r)
            allow = data.get("unattended_allow", [])
            if isinstance(allow, list):
                unattended_allow.extend(str(a) for a in allow if a)
        return local_enabled

    if global_config_path is None:
        global_config_path = Path.home() / ".agentwire" / "damagecontrol.yml"
    try:
        if global_config_path.exists():
            with open(global_config_path, "r") as f:
                gdata = yaml.safe_load(f) or {}
            genabled = _absorb(gdata)
            if genabled is not None:
                enabled = genabled
    except Exception:
        pass

    if cwd is None:
        cwd = os.environ.get("PWD", os.getcwd())
    current = os.path.abspath(cwd)
    while True:
        candidate = os.path.join(current, ".damagecontrol.yml")
        if os.path.isfile(candidate):
            try:
                with open(candidate, "r") as f:
                    pdata = yaml.safe_load(f) or {}
                project_enabled = _absorb(pdata)
            except Exception:
                pass
            break
        parent = os.path.dirname(current)
        if parent == current:
            break
        current = parent

    if project_enabled is not None:
        enabled = project_enabled

    return {
        "enabled": enabled,
        "disabled_rules": sorted(set(disabled_rules)),
        "unattended_allow": sorted(set(unattended_allow)),
    }


# ============================================================================
# PROTECTED CONTROL PLANE (escape-hatch- AND kill-switch-EXEMPT)
# ============================================================================
#
# Damage control reads its kill switch, its rules, and its own hook
# registration from files on disk. If the policed agent can write those files,
# it can disable safety, act, and re-enable — defeating everything (#466). So
# the WHOLE control plane is hard-protected: any write/edit/delete/move/chmod
# targeting one of these paths is BLOCKED, and — unlike every other rule — the
# ``# allow:`` escape hatch and the ``enabled: false`` kill switch do NOT
# override it. Only the user's ``allowedPaths`` allowlist can re-permit a path,
# because that is a human, host-side opt-in (the agent cannot add to it without
# editing a protected file, which is itself blocked).
#
# The guarantee: the agent only ever operates within the freedom the human
# preset. Loosening is always a host-side act.

PROTECTED_CONTROL_PLANE_PATHS = [
    "~/.agentwire/damagecontrol.yml",   # global kill switch + rule knobs
    "*.damagecontrol.yml",              # project kill switch + rule knobs (any dir)
    "~/.claude/settings.json",          # PreToolUse hook registration
    "~/.agentwire/hooks/damage-control/*.py",  # the hook scripts themselves
    "~/.claude/hooks/*",                # agentwire-owned Claude Code hooks
    "~/.agentwire/damage-control/*.yaml",      # the damage-control rule files
    # Execution-plane configs: agentwire runs strings from these files through
    # its OWN ``subprocess.run(..., shell=True)`` calls (scheduler gate commands
    # in scheduler.py, service healthchecks in services.py) — those subprocesses
    # do NOT traverse the Claude Code hook, so a policed agent that can write a
    # gate/healthcheck gets unguarded code execution on the next tick (a
    # confused-deputy escape). Treat them as control plane (#466 lockdown).
    "~/.agentwire/scheduler.yaml",      # scheduler gate commands run via shell
    "~/.agentwire/config.yaml",         # service healthcheck commands run via shell
    # Per-project task config: ``.agentwire.yml`` also defines task pre/post/gate
    # commands. Protecting it closes the same escape, with an ergonomic tradeoff —
    # under worktree dispatch the agent can no longer author its own task config,
    # so task authoring becomes a host-side act (consistent with the control-plane
    # guarantee: loosening is always host-side).
    "*.agentwire.yml",                  # project session/task config (any dir)
]


def _protected_path_patterns() -> List[str]:
    """Protected paths in both ``~``-form and ``$HOME``-expanded form.

    Commands may reference either; including both ensures the regex/glob
    matchers catch e.g. ``/Users/me/.claude/settings.json`` and
    ``~/.claude/settings.json`` alike.
    """
    out: List[str] = []
    for p in PROTECTED_CONTROL_PLANE_PATHS:
        out.append(p)
        expanded = os.path.expanduser(p)
        if expanded != p:
            out.append(expanded)
    return out


def is_protected_control_plane(file_path: str) -> bool:
    """True if ``file_path`` is part of the damage-control control plane."""
    for pat in _protected_path_patterns():
        if match_path(file_path, pat):
            return True
    return False


def check_protected_path(
    file_path: str,
    allowed_paths: List[Dict[str, Any]],
) -> Tuple[bool, str]:
    """Block edits/writes to a control-plane file unless the user allowlisted it.

    Used by the edit/write hooks. The allowlist (a human opt-in) may override;
    nothing else does.
    """
    if is_protected_control_plane(file_path):
        if is_path_allowed_for_op(file_path, allowed_paths, "edit"):
            return False, ""
        return True, "protected control-plane file (host-owned; edit on the host)"
    return False, ""


def check_protected_command(
    command: str,
    allowed_paths: List[Dict[str, Any]],
) -> Tuple[bool, str]:
    """Block a bash command that writes/edits/deletes a control-plane file.

    Mirrors the ``readOnlyPaths`` matcher but is escape-hatch- and
    kill-switch-exempt. The user's allowlist may re-permit a specific path.

    Matches against the raw command AND its normalized subcommands so quoting /
    escaping (``r\\m``, ``r''m``) can't sneak a write past the control-plane gate.
    """
    subcommands, _ambiguous = normalize_subcommands(command)
    haystacks = [command] + [s for s in subcommands if s and s != command]
    for path in _protected_path_patterns():
        for hay in haystacks:
            matched, reason = check_path_patterns(
                hay, path, READ_ONLY_BLOCKED, "protected control-plane path"
            )
            if matched:
                op = _infer_operation_from_reason(reason)
                if is_command_path_allowed(command, allowed_paths, op):
                    break
                return True, f"Protected control-plane path: {path}"
    return False, ""


_ESCAPE_HATCH_RE = re.compile(r"#\s*allow:[ \t]*([^\n]+)", re.IGNORECASE)


def detect_escape_hatch(command: str) -> Optional[str]:
    """Return the reason if ``command`` contains a ``# allow: <reason>`` marker.

    Non-empty reason required; matches the rest of the comment line so the
    marker works on multi-line / chained commands too.
    """
    if not command:
        return None
    m = _ESCAPE_HATCH_RE.search(command)
    if not m:
        return None
    reason = m.group(1).strip()
    return reason or None


# ============================================================================
# SHELL-AWARE NORMALIZATION
# ============================================================================
#
# The bash matcher historically ran the rule regexes against the RAW command
# string. With no tokenization, trivial shell quoting/escaping defeated every
# rule: ``r\m -rf /x`` (backslash), ``r''m -rf /x`` (empty quotes),
# ``R=rm; $R -rf /x`` ($VAR indirection) all read as ALLOWED while literal
# ``rm -rf /x`` blocked. We now ALSO match against a normalized form where
# quotes/escapes are removed (via ``shlex``) and simple ``$VAR`` assignments are
# resolved, split per subcommand. ``eval`` and a ``base64 -d | sh`` pipeline are
# unconditionally unverifiable and FAIL CLOSED (escalated to ``ask``, which the
# unattended resolver turns into a block).
#
# Command substitution (``$(...)`` / backticks) is handled position-aware (#502).
# Failing closed on ALL substitution over-blocked benign data-argument use that
# agents run constantly (``echo $(date)``, ``git log --since=$(date ...)``,
# ``cat "$(pwd)/file"``). Instead we MASK each substitution to one opaque token
# and apply an ALLOWLIST model: a masked substitution DEFAULTS to dangerous
# (escalate → ``ask``) and passes only when its position is affirmatively DATA.
# It is dangerous — i.e. its output can become an executed command word — when:
#   * it is the command word (argv-0) of a subcommand (``$(echo rm) -rf /`` — the
#     benign-looking inner is irrelevant, the *output* runs); or
#   * it is the argument of a command-consuming flag (``find -exec``/``-execdir``/
#     ``-ok``/``-okdir`` — ``find . -exec $(echo rm) {} +``); or
#   * it sits anywhere in ``argv[1:]`` of a head that is NOT a recognized
#     data-position command. This is the key inversion: command-wrappers that run
#     their args as a command (``sudo``, ``xargs``, ``ionice``, ``chrt``,
#     ``flock``, ``firejail``, ``setpriv`` …) are an unbounded set, so rather than
#     enumerate them we allow only the known-data heads (``_DATA_SAFE_HEADS``) and
#     fail SAFE on everything else.
# The static skeleton (substitution as one opaque token) is still fed through the
# normal rule ladder, so ``rm -rf $(...)`` is also caught there.

_EVAL_RE = re.compile(r"(?:^|[\s;&|({])eval(?:\s|$)")
_BASE64_PIPE_RE = re.compile(r"\bbase64\b[^\n|]*(?:-d|--decode)[^\n|]*\|", re.IGNORECASE)
_ASSIGN_RE = re.compile(
    r"(?:^|[\n;&|]|&&|\|\|)\s*([A-Za-z_]\w*)=('[^']*'|\"[^\"]*\"|[^\s;|&]*)"
)
_SHELL_OPERATORS = {";", "&&", "||", "|", "&", "\n", ";;", "|&"}

# Opaque stand-in for a masked command substitution. Alphanumeric + underscores
# so it survives shlex tokenization and never matches a path/rule on its own.
_SUBST_PLACEHOLDER = "__awsubst__"

# Substitution policy is an ALLOWLIST, not a blocklist (#502). Enumerating
# dangerous command-wrappers (``sudo``, ``xargs``, ``ionice``, ``chrt``,
# ``flock``, ``firejail``, ``setpriv``, ``proot`` …) is whack-a-mole — every one
# runs ``argv[1:]`` as a command, so a masked substitution there IS the command
# word, and the set is effectively unbounded. Instead we DEFAULT a masked
# substitution to dangerous (escalate → ``ask``) and allow it only when its
# position is affirmatively DATA: a substitution argument to one of these
# recognized non-wrapper, non-interpreter heads (text/file utilities + VCS
# read), where the substitution's output is consumed as a string/path/pattern
# and never executed. An unknown head ⇒ ask (fail safe), not allow (fail open).
_DATA_SAFE_HEADS = {
    "echo", "printf", "cat", "tac", "ls", "grep", "egrep", "fgrep", "zgrep",
    "rg", "ag", "head", "tail", "test", "[", "git", "tar", "sort", "uniq",
    "wc", "cut", "tr", "diff", "comm", "jq", "yq", "basename", "dirname",
    "realpath", "readlink", "stat", "file", "du", "df", "date", "pwd", "find",
    "fd", "column", "nl", "fold", "rev", "paste", "join", "expand", "seq",
}

# Flags whose FOLLOWING argument is a command word that the tool will execute —
# the substitution there is run, not passed as data (``find ... -exec $(echo rm)
# {} +`` smuggles a masked ``rm`` into find's command slot). Checked for EVERY
# head (incl. data-safe ``find``), before the data-position allow (#502).
_COMMAND_CONSUMING_FLAGS = {
    "-exec", "-execdir", "-ok", "-okdir",
}


def _mask_substitutions(command: str) -> Tuple[str, bool, bool]:
    """Replace each ``$(...)`` / ```...``` with a placeholder token.

    Returns ``(masked, had_substitution, unbalanced)``. ``unbalanced`` is True
    when a substitution is opened but never closed (we fail closed on it). Nested
    ``$(...)`` parens are balanced; arithmetic ``$((...))`` is masked too (it is
    inert data, never command position).
    """
    out: List[str] = []
    i = 0
    n = len(command)
    had = False
    while i < n:
        c = command[i]
        if c == "`":
            j = command.find("`", i + 1)
            if j == -1:
                return "".join(out) + command[i:], True, True
            out.append(_SUBST_PLACEHOLDER)
            had = True
            i = j + 1
        elif c == "$" and i + 1 < n and command[i + 1] == "(":
            depth = 1
            j = i + 2
            while j < n and depth > 0:
                if command[j] == "(":
                    depth += 1
                elif command[j] == ")":
                    depth -= 1
                j += 1
            if depth != 0:
                return "".join(out) + command[i:], True, True
            out.append(_SUBST_PLACEHOLDER)
            had = True
            i = j
        else:
            out.append(c)
            i += 1
    return "".join(out), had, False


def _has_subst(tok: str) -> bool:
    return _SUBST_PLACEHOLDER in tok


def _dangerous_substitution(subcommands_tokens: List[List[str]]) -> Optional[str]:
    """Return a reason if any masked substitution sits in a dangerous position.

    ``subcommands_tokens`` is the per-subcommand token list (placeholders intact).
    """
    for toks in subcommands_tokens:
        if not toks:
            continue
        # Substitution in command position — its output is what runs.
        if _has_subst(toks[0]):
            return "command substitution in command position"
        # Substitution landing in a command-consuming flag's argument (the
        # command word that ``find -exec`` / ``-ok`` / … will run). Checked for
        # every head, since data-safe ``find`` still has exec slots.
        for i, tok in enumerate(toks[:-1]):
            if tok.strip("'\"") in _COMMAND_CONSUMING_FLAGS and _has_subst(toks[i + 1]):
                return "command substitution in a command-consuming argument"
        # Any other substitution in argv[1:]: allow ONLY when the head is a
        # recognized data-position command; otherwise it may be a command-wrapper
        # whose argument becomes the executed command — fail safe to ``ask``.
        if any(_has_subst(t) for t in toks[1:]):
            head = os.path.basename(toks[0].strip("'\""))
            if head not in _DATA_SAFE_HEADS:
                return "command substitution argument to an unrecognized command (possible wrapper)"
    return None


def detect_obfuscation(command: str) -> Optional[str]:
    """Return a reason string if ``command`` hides intent behind shell features.

    ``eval`` and ``base64 -d | sh`` are unconditionally unverifiable — they run
    their argument/stdin as code, so we decline to reason about them and fail
    closed. Command substitution is NOT flagged here; it is handled position-aware
    in :func:`normalize_subcommands` (#502).
    """
    if _EVAL_RE.search(command):
        return "eval"
    if _BASE64_PIPE_RE.search(command):
        return "base64-decode pipeline"
    return None


def normalize_subcommands(command: str) -> Tuple[List[str], Optional[str]]:
    """Tokenize ``command`` and return ``(normalized_subcommands, ambiguous)``.

    ``normalized_subcommands`` is the per-subcommand argv re-joined with single
    spaces, after command substitutions have been masked to an opaque token,
    ``shlex`` has stripped quotes/escapes, and simple ``$VAR`` assignments earlier
    in the same command have been resolved. ``ambiguous`` is a reason string when
    the command can't be verified safely (and the caller should fail closed); it
    is ``None`` on success. Benign data-argument substitution returns its masked
    skeleton with ``ambiguous=None`` so the normal rule ladder still inspects it.
    """
    obf = detect_obfuscation(command)
    if obf:
        return [], obf

    masked, had_subst, unbalanced = _mask_substitutions(command)
    if unbalanced:
        return [], "unbalanced command substitution"

    # Resolve simple ``VAR=value`` assignments so ``R=rm; $R -rf`` normalizes to
    # ``rm -rf``. Only literal values (no nested expansion) are resolved.
    assigns: Dict[str, str] = {}
    for m in _ASSIGN_RE.finditer(masked):
        assigns[m.group(1)] = m.group(2).strip("'\"")

    try:
        lex = shlex.shlex(masked, posix=True, punctuation_chars=True)
        lex.whitespace_split = True
        tokens = list(lex)
    except ValueError:
        return [], "unbalanced quotes"

    def _resolve(tok: str) -> str:
        for name, val in assigns.items():
            tok = tok.replace("${%s}" % name, val).replace("$" + name, val)
        return tok

    subs: List[str] = []
    sub_tokens: List[List[str]] = []
    cur: List[str] = []
    for tok in tokens:
        if tok in _SHELL_OPERATORS:
            if cur:
                subs.append(" ".join(cur))
                sub_tokens.append(cur)
                cur = []
            continue
        cur.append(_resolve(tok))
    if cur:
        subs.append(" ".join(cur))
        sub_tokens.append(cur)

    ambiguous = _dangerous_substitution(sub_tokens) if had_subst else None
    return subs, ambiguous


# ============================================================================
# DECISION LADDERS
# ============================================================================


def check_command(command: str, config: Dict[str, Any]) -> Dict[str, Any]:
    """Decide whether a bash command should be allowed/blocked/asked.

    Returns ``{decision, reason, pattern, command}`` plus optional ``id``,
    ``escape_reason``, ``escape``, ``disabled``.

    Order:
      0. Protected control plane → BLOCK (escape-hatch- AND kill-switch-exempt;
         only the user's allowlist re-permits) — runs FIRST so an agent can't
         self-authorize a write to the files that gate everything else.
      1. Escape hatch (``# allow: <reason>``) → ALLOW (escape=True)
      2. Kill switch (``config["safety"]["enabled"] is False``) → ALLOW (disabled=True)
      3. Hard-blocked bash patterns (skip if ``id`` in ``disabled_rules``)
      4. Ask patterns
      5. Bypassable bash patterns → check allowlist for required operation
      6. zeroAccessPaths → check allowlist with ``read`` permission
      7. readOnlyPaths → match against READ_ONLY_BLOCKED operation patterns
      8. noDeletePaths → match against NO_DELETE_BLOCKED patterns
    """
    safety_cfg = config.get("safety", {}) if isinstance(config.get("safety"), dict) else {}
    disabled_rules = set(safety_cfg.get("disabled_rules", []) or [])
    is_enabled = safety_cfg.get("enabled", True)

    allowed = load_allowed_paths(config)

    # Protected control plane FIRST — before the escape hatch and the kill
    # switch. An agent must never be able to self-authorize a write to the
    # files that define safety itself (#466).
    prot_blocked, prot_reason = check_protected_command(command, allowed)
    if prot_blocked:
        return {
            "decision": "block",
            "reason": prot_reason,
            "pattern": "protectedControlPlane",
            "command": command,
            "protected": True,
        }

    # Parser unavailable ⇒ no rules loaded ⇒ fail closed (block), before the
    # escape hatch / kill switch can wave it through.
    if config.get("_parser_unavailable"):
        return {
            "decision": "block",
            "reason": str(config["_parser_unavailable"]),
            "pattern": "parserUnavailable",
            "command": command,
        }

    escape_reason = detect_escape_hatch(command)
    if escape_reason:
        return {
            "decision": "allow",
            "reason": f"Escape hatch: {escape_reason}",
            "pattern": None,
            "command": command,
            "escape": True,
            "escape_reason": escape_reason,
        }

    if is_enabled is False:
        return {
            "decision": "allow",
            "reason": "safety disabled",
            "pattern": None,
            "command": command,
            "disabled": True,
        }

    bash_patterns = config.get("bashToolPatterns", [])
    zero_access = config.get("zeroAccessPaths", [])
    read_only = config.get("readOnlyPaths", [])
    no_delete = config.get("noDeletePaths", [])

    # Match rules against the raw command AND its normalized subcommands, so a
    # quoting/escaping/$VAR trick (``r\m``, ``r''m``, ``R=rm; $R -rf``) is caught
    # the same as the literal form. ``ambiguous`` is set when the command hides
    # behind substitution/eval/base64-pipe/unbalanced-quotes — we fail closed to
    # ``ask`` at the end (the unattended resolver turns that into a block).
    subcommands, ambiguous = normalize_subcommands(command)
    haystacks = [command] + [s for s in subcommands if s and s != command]

    def _search(pat: str) -> bool:
        for hay in haystacks:
            try:
                if re.search(pat, hay, re.IGNORECASE):
                    return True
            except re.error:
                return False
        return False

    bypassable_matches: List[Tuple[str, str, Optional[str]]] = []

    for pattern_obj in bash_patterns:
        if not isinstance(pattern_obj, dict):
            continue
        rule_id = pattern_obj.get("id")
        if rule_id and rule_id in disabled_rules:
            continue
        pattern = pattern_obj.get("pattern", "")
        reason = pattern_obj.get("reason", "Matched pattern")
        should_ask = pattern_obj.get("ask", False)
        bypassable = pattern_obj.get("bypassable", False)
        try:
            if _search(pattern):
                if should_ask:
                    return {
                        "decision": "ask",
                        "reason": reason,
                        "pattern": pattern,
                        "command": command,
                        "id": rule_id,
                    }
                elif bypassable:
                    bypassable_matches.append((pattern, reason, rule_id))
                else:
                    return {
                        "decision": "block",
                        "reason": reason,
                        "pattern": pattern,
                        "command": command,
                        "id": rule_id,
                    }
        except re.error:
            continue

    for pattern, reason, rule_id in bypassable_matches:
        operation = _infer_operation_from_reason(reason)
        if not is_command_path_allowed(command, allowed, operation):
            return {
                "decision": "block",
                "reason": reason,
                "pattern": pattern,
                "command": command,
                "id": rule_id,
            }

    for path in zero_access:
        if any(matches_path_in_command(path, hay) for hay in haystacks):
            if is_command_path_allowed(command, allowed, "read"):
                continue
            return {
                "decision": "block",
                "reason": f"Zero-access path: {path}",
                "pattern": f"zeroAccessPath: {path}",
                "command": command,
            }

    for path in read_only:
        op = None
        for hay in haystacks:
            matched, reason = check_path_patterns(hay, path, READ_ONLY_BLOCKED, "read-only path")
            if matched:
                op = _infer_operation_from_reason(reason)
                break
        if op is not None:
            if is_command_path_allowed(command, allowed, op):
                continue
            return {
                "decision": "block",
                "reason": f"Read-only path: {path}",
                "pattern": f"readOnlyPath: {path}",
                "command": command,
            }

    for path in no_delete:
        if any(
            check_path_patterns(hay, path, NO_DELETE_BLOCKED, "no-delete path")[0]
            for hay in haystacks
        ):
            if is_command_path_allowed(command, allowed, "delete"):
                continue
            return {
                "decision": "block",
                "reason": f"No-delete path: {path}",
                "pattern": f"noDeletePath: {path}",
                "command": command,
            }

    # Nothing matched. If the command hid behind substitution/eval/etc. we could
    # not verify it statically — fail closed to ``ask`` (a block when unattended).
    if ambiguous:
        return {
            "decision": "ask",
            "reason": f"Unverifiable command ({ambiguous}) — confirm before running",
            "pattern": f"ambiguous:{ambiguous}",
            "command": command,
            "id": "core.ambiguous-command",
        }

    return {
        "decision": "allow",
        "reason": "No patterns matched",
        "pattern": None,
        "command": command,
    }


def check_path(file_path: str, config: Dict[str, Any]) -> Tuple[bool, str]:
    """File-path-only check used by edit/write hooks. Returns ``(blocked, reason)``.

    The protected control plane is checked FIRST, before the kill switch — the
    files that gate safety stay agent-unwritable even when safety is disabled;
    only the user's allowlist re-permits them (#466).
    """
    allowed = load_allowed_paths(config)

    prot_blocked, prot_reason = check_protected_path(file_path, allowed)
    if prot_blocked:
        return True, prot_reason

    safety_cfg = config.get("safety", {}) if isinstance(config.get("safety"), dict) else {}
    if safety_cfg.get("enabled", True) is False:
        return False, ""

    if is_path_allowed_for_op(file_path, allowed, "edit"):
        return False, ""

    for zero_path in config.get("zeroAccessPaths", []):
        if match_path(file_path, zero_path):
            return True, f"zero-access path {zero_path} (no operations allowed)"

    for readonly in config.get("readOnlyPaths", []):
        if match_path(file_path, readonly):
            return True, f"read-only path {readonly}"

    return False, ""


def check_read_path(file_path: str, config: Dict[str, Any]) -> Tuple[bool, str]:
    """File-path-only check for content-reading tools (Read/Grep/Glob).

    The Bash/Edit/Write hooks never see native ``Read``/``Grep``/``Glob`` tool
    calls, so a ``zeroAccessPaths`` secret (``~/.agentwire/.env``, ``~/.ssh/id_rsa``,
    ``*.pem``) could be exfiltrated by reading it directly. Claude Code fires a
    blocking ``PreToolUse`` hook for these tools too, so the read-tool hook runs
    ``file_path`` through this check and blocks a zero-access read.

    Only ``zeroAccessPaths`` deny reads — ``readOnlyPaths`` are readable by
    definition, and the control plane is host-owned config the agent may read
    (only its *writes* are blocked). The kill switch disables this like any other
    rule; the allowlist (a human opt-in) re-permits a specific read.
    """
    allowed = load_allowed_paths(config)
    if is_path_allowed_for_op(file_path, allowed, "read"):
        return False, ""

    safety_cfg = config.get("safety", {}) if isinstance(config.get("safety"), dict) else {}
    if safety_cfg.get("enabled", True) is False:
        return False, ""

    for zero_path in config.get("zeroAccessPaths", []):
        if match_path(file_path, zero_path):
            return True, f"zero-access path {zero_path} (no read access)"

    return False, ""
# === END GENERATED ===


# ============================================================================
# HOOK ENTRY POINT
# ============================================================================


def _resolve_rules_dir() -> Path:
    user_dir = Path(os.environ.get("AGENTWIRE_DIR", os.path.expanduser("~/.agentwire")))
    user_rules = user_dir / "damage-control"
    if user_rules.exists() and any(user_rules.glob("*.yaml")):
        return user_rules
    return Path(__file__).parent / "rules"


def main() -> None:
    config = load_config(_resolve_rules_dir())
    config["safety"] = load_safety_config()

    try:
        input_data = json.load(sys.stdin)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON input: {e}", file=sys.stderr)
        sys.exit(1)

    tool_name = input_data.get("tool_name", "")
    tool_input = input_data.get("tool_input", {})

    if tool_name != "Write":
        sys.exit(0)

    file_path = tool_input.get("file_path", "")
    if not file_path:
        sys.exit(0)

    # check_path enforces the protected control plane even when safety is
    # disabled, so it must run BEFORE the kill-switch short-circuit (#466).
    blocked, reason = check_path(file_path, config)
    if blocked:
        log_blocked("Write", file_path, reason)
        print(f"SECURITY: Blocked write to {reason}: {file_path}", file=sys.stderr)
        sys.exit(2)

    if config["safety"].get("enabled", True) is False:
        log_disabled("Write", file_path)
        sys.exit(0)

    log_allowed("Write", file_path, user_approved=False)
    sys.exit(0)


if __name__ == "__main__":
    main()
