"""The resume dialog: detection, routing, root escalation, doctor (#905).

THE FIXTURE IS THE POINT OF THIS FILE. ``RESUME_DIALOG`` is
``tmux capture-pane -p`` output **from a 200-column pane** genuinely sitting at
this dialog, reproduced on 2026-08-05 by resuming a cloned 134k-token
conversation with the gating feature flag enabled in an isolated ``HOME``. The
option labels and body sentence were cross-checked against the string literals
in the shipped Claude Code binary (2.1.222), so they are the product's text and
not a transcription of a screenshot.

**Always record the capture width**, right next to the capture. The dialog's
body sentence is 122 columns, so it is unwrapped only on a pane wider than
that, and every narrower pane breaks a line inside it. The first version of
this file pasted that 122-column body next to an 80-column rule — a screen no
capture can produce — and the detector it exercised located its anchor with a
plain ``str.index``, which raised ``ValueError`` at 54 of the 101 widths
between 40 and 140. A single comment naming the width would have made that
visible at review time without anyone running a sweep.

So every wrapped case here is generated by :func:`render_at_width` rather than
hand-reflowed, and the width sweep asserts DETECTION at each width, not merely
the absence of an exception — with the per-pane guard in place, a broken
detector produces silent misses rather than crashes, which is strictly harder
to diagnose and would sail past an "it didn't raise" assertion.

That is the same lesson as #901 (single-launch), #898 (single-pane) and #902
(flat session names): the fixture decides what the suite can see. Here it
applied twice — first to the dialog shape that had no fixture at all, then to
the pane width that every fixture happened to share.
"""

import json
import textwrap
from datetime import datetime, timedelta
from types import SimpleNamespace

import pytest

from agentwire import prompt_router
from agentwire.prompt_router import PromptInfo, detect_prompt

# =============================================================================
# Fixtures — real captures, verbatim
# =============================================================================

# From the real capture, taken on a 200-column pane. The only edit is that the
# transcript ABOVE the rule was trimmed to one line; every line from the rule
# down is byte-for-byte what tmux emitted, including the 200-column rule and
# the trailing blank lines tmux pads the pane height with (the liveness check
# anchors on the END of the screen, so stripping those tests a screen that
# never occurs).
#
# The width matters and is the reason this constant is not the whole story:
# the body sentence is 122 columns, so it fits UNWRAPPED only on a pane this
# wide. Narrower panes — 80 and 64 columns are what this fleet actually runs —
# break a line inside it. See RESUME_DIALOG_AT_92 and the width sweep below;
# an earlier version of this file had an 80-column rule beside the 122-column
# body, a combination no capture can produce, and that reflow is exactly why
# nothing here exercised wrapping.
RESUME_DIALOG = """\
⏺ Read 2 files, ran 4 shell commands
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  This session is 2m old and 134.1k tokens.

  Resuming the full session will consume a substantial portion of your usage limits. We recommend resuming from a summary.

  ❯ 1. Resume from summary (recommended)
    2. Resume full session as-is
    3. Don't ask me again

  Enter to confirm · Esc to cancel

"""


def render_at_width(screen: str, width: int) -> str:
    """Re-render *screen* as a pane of *width* columns would show it.

    Hard-wraps every over-long line, preserving the leading indent on
    continuations the way the dialog's own renderer does. This is the fixture
    generator the first version of this file lacked.
    """
    out = []
    for line in screen.split("\n"):
        if len(line) <= width:
            out.append(line)
            continue
        indent = " " * (len(line) - len(line.lstrip()))
        out += textwrap.wrap(line, width, subsequent_indent=indent) or [line]
    return "\n".join(out)


# The same dialog on a 92-column pane. A line break lands inside the anchor
# sentence, which is the case that used to raise ValueError out of the
# detector — and out of the whole sweep with it.
RESUME_DIALOG_AT_92 = render_at_width(RESUME_DIALOG, 92)

# The same dialog after four hours on a big conversation — the two numbers in
# the title are the ONLY difference, and they are formatted at render time.
RESUME_DIALOG_OLDER = RESUME_DIALOG.replace(
    "This session is 2m old and 134.1k tokens.",
    "This session is 2h 47m old and 233.6k tokens.",
)

# A pane DISPLAYING the dialog text rather than showing it: a session that was
# told about the incident, or one reading this very issue. It has its own input
# box and status bar below, so the screen does not end at the dialog footer.
# This is not hypothetical — the pane writing this test had the dialog quoted
# on screen from the task description.
QUOTED_RESUME_DIALOG = RESUME_DIALOG.rstrip() + """

  Enter to confirm · Esc to cancel  <- quoted from the issue, not live

────────────────────────────────────────────────────────────────────────────────
❯
────────────────────────────────────────────────────────────────────────────────
  ~/worktrees/agentwire-dev/fix-905                  claude-opus-5  $1.20  9m
"""


@pytest.fixture(autouse=True)
def isolated_router(tmp_path, monkeypatch):
    """Markers, events and email all land in the fixture, never the real home."""
    monkeypatch.setattr(prompt_router, "STATE_DIR", tmp_path / "prompt-router")
    monkeypatch.setattr(
        prompt_router, "EVENTS_FILE", tmp_path / "prompt-router-events.jsonl")
    prompt_router.STATE_DIR.mkdir(parents=True)


@pytest.fixture
def sent_emails(monkeypatch):
    """Capture owner escalations instead of sending them."""
    sent = []

    def fake_send_email(**kw):
        sent.append(kw)
        return SimpleNamespace(success=True, id="test-stub")

    monkeypatch.setattr("agentwire.channels.email.send_email", fake_send_email)
    return sent


# =============================================================================
# Detection
# =============================================================================


class TestDetection:
    def test_the_real_dialog_is_detected(self):
        """The bug: this returned None, so nothing downstream ever ran."""
        info = detect_prompt(RESUME_DIALOG)
        assert info is not None
        assert info.kind == "resume"

    def test_all_three_options_are_parsed(self):
        info = detect_prompt(RESUME_DIALOG)
        assert [(o["number"], o["label"]) for o in info.options] == [
            (1, "Resume from summary (recommended)"),
            (2, "Resume full session as-is"),
            (3, "Don't ask me again"),
        ]

    def test_age_and_tokens_are_reported_as_context(self):
        assert detect_prompt(RESUME_DIALOG).summary == (
            "session is 2m old, 134.1k tokens")
        assert detect_prompt(RESUME_DIALOG_OLDER).summary == (
            "session is 2h 47m old, 233.6k tokens")

    def test_the_hash_ignores_the_ticking_age(self):
        """Otherwise every sweep sees a NEW prompt and re-notifies the parent.

        The title interpolates age and token count. If those reached the
        content hash, a dialog that redrew would defeat the presence-marker
        dedupe and paste into the parent every 60 seconds.
        """
        assert (detect_prompt(RESUME_DIALOG).content_hash()
                == detect_prompt(RESUME_DIALOG_OLDER).content_hash())

    def test_a_quoted_dialog_is_not_detected(self):
        """A pane merely SHOWING this text must never be routed as blocked."""
        assert detect_prompt(QUOTED_RESUME_DIALOG) is None

    def test_a_delivered_notification_is_not_re_detected(self):
        """The loop guard: our own message quotes the option labels."""
        info = detect_prompt(RESUME_DIALOG)
        message = prompt_router.build_message("worker", 0, info)
        assert detect_prompt(message + "\n\n Enter to confirm · Esc to cancel") is None

    def test_it_does_not_shadow_the_other_dialog_kinds(self):
        """_detect_resume runs first; the existing three must still classify."""
        from tests.unit.test_prompt_router import (
            PERMISSION_BASH,
            PLAN_APPROVAL,
            QUESTION_SIMPLE,
            QUESTION_TABBED,
        )

        assert detect_prompt(PERMISSION_BASH).kind == "permission"
        assert detect_prompt(PLAN_APPROVAL).kind == "plan"
        assert detect_prompt(QUESTION_SIMPLE).kind == "question"
        assert detect_prompt(QUESTION_TABBED).kind == "question"

    def test_the_footer_alone_is_not_enough(self):
        """The usage-limit dialog shares this exact footer."""
        from tests.unit.test_prompt_router import USAGE_LIMIT_DIALOG

        assert detect_prompt(USAGE_LIMIT_DIALOG) is None

    def test_the_body_sentence_is_122_columns_wide(self):
        """Pins the premise the wrap tests rest on.

        If a future Claude Code shortens this sentence below the common pane
        widths, the wrap cases below stop exercising anything and should be
        re-derived rather than left passing vacuously.
        """
        body = next(ln for ln in RESUME_DIALOG.split("\n")
                    if "Resuming the full session" in ln)
        assert len(body) == 122

    def test_a_92_column_pane_is_detected(self):
        """The blocking bug: a line break inside the anchor.

        The anchor was tested against NORMALIZED text (wrap-insensitive, so it
        passed) and then located with `str.index` on the UN-normalized capture
        (wrap-sensitive, so it raised ValueError). 92 columns puts a break
        inside "We recommend resuming from a summary."
        """
        info = detect_prompt(RESUME_DIALOG_AT_92)
        assert info is not None
        assert info.kind == "resume"
        assert len(info.options) == 3

    def test_the_anchor_really_is_broken_at_92_columns(self):
        """Guards the guard — a fixture that didn't wrap would pass anyway."""
        assert "We recommend resuming from a summary." not in RESUME_DIALOG_AT_92
        assert "We recommend resuming from a summary." in RESUME_DIALOG

    @pytest.mark.parametrize("width", [64, 80, 92, 100, 120, 131])
    def test_the_pane_widths_this_fleet_actually_runs(self, width):
        """64, 80 and 131 were live pane widths on the machine that hit #905."""
        info = detect_prompt(render_at_width(RESUME_DIALOG, width))
        assert info is not None, f"undetected at {width} columns"
        assert [o["number"] for o in info.options] == [1, 2, 3]

    def test_no_width_crashes_and_none_silently_misses(self):
        """Every plausible pane width, swept.

        Before the fix: 54 of these 101 widths raised ValueError out of
        `detect_prompt` — and, because the sweep had no per-pane guard, out of
        the entire sweep with it. A single test at one width could not see
        that, which is the whole lesson.
        """
        crashed, missed = [], []
        for width in range(40, 141):
            try:
                if detect_prompt(render_at_width(RESUME_DIALOG, width)) is None:
                    missed.append(width)
            except Exception as exc:
                crashed.append((width, type(exc).__name__, str(exc)))
        assert crashed == [], f"{len(crashed)} width(s) raised: {crashed[:3]}"
        assert missed == [], f"{len(missed)} width(s) undetected: {missed[:10]}"

    def test_the_hash_survives_a_re_wrap(self):
        """A pane resize must not look like a brand-new prompt."""
        wide = detect_prompt(RESUME_DIALOG).content_hash()
        assert detect_prompt(RESUME_DIALOG_AT_92).content_hash() == wide
        assert detect_prompt(render_at_width(RESUME_DIALOG, 64)).content_hash() == wide

    def test_the_footer_is_not_swallowed_as_an_option_description(self):
        """`parse_ask_options` treats the next non-blank line as a description,
        and the hint footer follows option 3."""
        for screen in (RESUME_DIALOG, RESUME_DIALOG_AT_92):
            options = detect_prompt(screen).options
            assert all("Enter to confirm" not in o["description"] for o in options)
            assert options[-1]["description"] == ""

    def test_a_quoted_dialog_is_still_rejected_when_wrapped(self):
        """The wrap tolerance must not cost us the false-positive guard."""
        for width in (64, 80, 92, 131):
            assert detect_prompt(render_at_width(QUOTED_RESUME_DIALOG, width)) is None

    def test_the_anchor_alone_is_not_enough(self):
        """Body text with no live menu under it is prose, not a dialog."""
        prose = (
            "I hit the resume dialog. We recommend resuming from a summary.\n"
            "Anyway, moving on.\n"
        )
        assert detect_prompt(prose) is None


# =============================================================================
# Routing to a parent
# =============================================================================


class TestRouting:
    def test_a_blocked_worker_reaches_its_parent(self, monkeypatch):
        """End to end: the exact state that stranded four sessions."""
        delivered = []
        monkeypatch.setattr(
            prompt_router, "resolve_parent", lambda *a, **k: ("orch", 0))
        monkeypatch.setattr(
            prompt_router, "safe_deliver",
            lambda s, p, text: (delivered.append((s, p, text)), (True, "delivered"))[1])

        info = detect_prompt(RESUME_DIALOG)
        assert prompt_router.route_prompt("worker", 0, info) == "orch"

        target_session, target_pane, text = delivered[0]
        assert (target_session, target_pane) == ("orch", 0)
        assert "kind=resume" in text
        assert "134.1k tokens" in text
        assert "agentwire prompts answer" in text
        assert info.content_hash() in text

    def test_the_notification_is_answerable_as_captured(self, monkeypatch):
        """The hash in the message must match what `prompts answer` re-derives."""
        monkeypatch.setattr(prompt_router, "_capture", lambda t, **k: RESUME_DIALOG)
        sent = []
        monkeypatch.setattr(prompt_router, "_tmux", lambda args, **k: sent.append(args)
                            or SimpleNamespace(returncode=0, stdout=""))

        info = detect_prompt(RESUME_DIALOG)
        ok, reason = prompt_router.answer(
            "worker", 0, info.content_hash(), ["1"])
        assert ok, reason

    def test_a_stale_hash_refuses_to_answer(self, monkeypatch):
        monkeypatch.setattr(prompt_router, "_capture", lambda t, **k: RESUME_DIALOG)
        ok, reason = prompt_router.answer("worker", 0, "0000000000000000", ["1"])
        assert not ok


# =============================================================================
# The root case — no parent to route to
# =============================================================================


class TestRootEscalation:
    def test_a_root_session_emails_the_owner(self, monkeypatch, sent_emails):
        """no_parent used to be terminal: marker written, nobody told."""
        monkeypatch.setattr(prompt_router, "resolve_parent", lambda *a, **k: None)

        info = detect_prompt(RESUME_DIALOG)
        assert prompt_router.route_prompt("documentscribe", 0, info) is None

        assert len(sent_emails) == 1
        assert "documentscribe" in sent_emails[0]["subject"]
        body = sent_emails[0]["body"]
        assert "no parent" in body
        assert "agentwire prompts answer -s 'documentscribe'" in body
        assert info.content_hash() in body

    def test_the_marker_records_the_escalation(self, monkeypatch, sent_emails):
        monkeypatch.setattr(prompt_router, "resolve_parent", lambda *a, **k: None)
        prompt_router.route_prompt("root", 0, detect_prompt(RESUME_DIALOG))
        marker = prompt_router.read_marker("root", 0)
        assert marker["status"] == "no_parent"
        assert marker["escalated_at"]

    def test_the_sweeps_60s_cadence_does_not_become_60_emails_an_hour(
            self, monkeypatch, sent_emails):
        """A no-parent prompt is re-routed EVERY tick — nothing sets
        notified_at, so the sweep never short-circuits on it."""
        monkeypatch.setattr(prompt_router, "resolve_parent", lambda *a, **k: None)
        info = detect_prompt(RESUME_DIALOG)
        for _ in range(10):
            prompt_router.route_prompt("root", 0, info)
        assert len(sent_emails) == 1

    def test_it_nags_again_once_the_ttl_expires(self, monkeypatch, sent_emails):
        """Four hours of silence is the failure; one email then quiet is not
        much better."""
        monkeypatch.setattr(prompt_router, "resolve_parent", lambda *a, **k: None)
        info = detect_prompt(RESUME_DIALOG)
        prompt_router.route_prompt("root", 0, info)

        marker = prompt_router.read_marker("root", 0)
        old = datetime.fromisoformat(marker["escalated_at"]) - timedelta(hours=2)
        marker["escalated_at"] = old.isoformat()
        marker["detected_at"] = old.isoformat()
        prompt_router.write_marker("root", 0, **{
            k: v for k, v in marker.items() if k not in ("session", "pane")})

        prompt_router.route_prompt("root", 0, info)
        assert len(sent_emails) == 2
        assert "waiting 120 minutes" in sent_emails[1]["body"]

    def test_how_long_it_has_been_blocked_survives_the_rewrite(
            self, monkeypatch, sent_emails):
        """detected_at used to be refreshed on every tick, so a pane blocked
        for four hours read as seconds old to anything measuring the wait."""
        monkeypatch.setattr(prompt_router, "resolve_parent", lambda *a, **k: None)
        info = detect_prompt(RESUME_DIALOG)
        prompt_router.route_prompt("root", 0, info)
        first = prompt_router.read_marker("root", 0)["detected_at"]

        for _ in range(5):
            prompt_router.route_prompt("root", 0, info)
        assert prompt_router.read_marker("root", 0)["detected_at"] == first

    def test_a_different_prompt_restarts_the_clock(self, monkeypatch, sent_emails):
        monkeypatch.setattr(prompt_router, "resolve_parent", lambda *a, **k: None)
        prompt_router.route_prompt("root", 0, detect_prompt(RESUME_DIALOG))
        first = prompt_router.read_marker("root", 0)

        other = PromptInfo(kind="question", question="Ship it?",
                           options=[{"number": 1, "label": "Yes"}])
        prompt_router.route_prompt("root", 0, other)
        assert prompt_router.read_marker("root", 0)["detected_at"] != first["detected_at"]
        assert len(sent_emails) == 2

    def test_a_failing_mailer_never_breaks_the_sweep(self, monkeypatch):
        def boom(**kw):
            raise RuntimeError("resend is down")

        monkeypatch.setattr("agentwire.channels.email.send_email", boom)
        monkeypatch.setattr(prompt_router, "resolve_parent", lambda *a, **k: None)

        assert prompt_router.route_prompt("root", 0, detect_prompt(RESUME_DIALOG)) is None
        assert prompt_router.read_marker("root", 0)["status"] == "no_parent"

    def test_a_parented_session_does_not_email(self, monkeypatch, sent_emails):
        monkeypatch.setattr(prompt_router, "resolve_parent", lambda *a, **k: ("orch", 0))
        monkeypatch.setattr(prompt_router, "safe_deliver", lambda *a: (True, "delivered"))
        prompt_router.route_prompt("worker", 0, detect_prompt(RESUME_DIALOG))
        assert sent_emails == []


# =============================================================================
# The sweep + the doctor check
# =============================================================================


def _fake_tmux(panes, screens):
    """A tmux stub: `list-panes -a` rows plus per-pane capture output."""
    rows = "\n".join("\t".join(str(c) for c in p) for p in panes)

    def run(args, **kwargs):
        if args and args[0] == "list-panes":
            return SimpleNamespace(returncode=0, stdout=rows)
        if args and args[0] == "capture-pane":
            target = args[args.index("-t") + 1]
            return SimpleNamespace(returncode=0, stdout=screens.get(target, ""))
        return SimpleNamespace(returncode=0, stdout="")

    return run


@pytest.fixture
def fleet(monkeypatch):
    """Two agent panes and a shell pane; only the blocked one shows a dialog.

    Pane indices are 0 and 1 on purpose — base-index ships as 0 since #903 but
    windows created before it kept 1, so both conventions are live at once and
    nothing may assume either.
    """
    panes = [
        ("blocked", 1, "node", "/repo/a"),
        ("healthy", 0, "node", "/repo/b"),
        ("a-shell", 0, "zsh", "/repo/c"),
    ]
    screens = {
        "blocked.1": RESUME_DIALOG,
        "healthy.0": "⏺ working away\n\n───\n❯\n───\n",
        # A shell pane that happens to be displaying the dialog text — `cat` of
        # a saved capture. It must never be treated as a blocked agent.
        "a-shell.0": RESUME_DIALOG,
    }
    monkeypatch.setattr(prompt_router, "_tmux", _fake_tmux(panes, screens))
    monkeypatch.setattr(prompt_router, "_capture",
                        lambda t, **k: screens.get(t, ""))
    monkeypatch.setattr(prompt_router, "_is_parked", lambda s: False)
    monkeypatch.setattr(prompt_router, "_router_config", lambda: (True, set()))
    return screens


class TestSweep:
    def test_the_sweep_routes_the_blocked_pane(self, fleet, monkeypatch):
        monkeypatch.setattr(prompt_router, "resolve_parent", lambda *a, **k: ("orch", 0))
        monkeypatch.setattr(prompt_router, "safe_deliver", lambda *a: (True, "delivered"))

        result = prompt_router.sweep()
        assert [(r["session"], r["pane"], r["kind"]) for r in result["routed"]] == [
            ("blocked", 1, "resume")]

    def test_one_crashing_pane_does_not_cost_the_fleet_its_routing(
            self, fleet, monkeypatch):
        """The blast radius that made the wrap bug worse than #905 itself.

        The sweep's pane loop had no guard, so a raise abandoned every
        REMAINING pane and the marker GC — and `limits_cli`'s stage isolation
        swallowed it and substituted an empty result. One unluckily-sized pane
        silently disabled permission, plan AND question routing fleet-wide.
        """
        # A DISTINCT screen, so the crash injection can tell them apart —
        # and the survivor is the wrapped rendering, which is the one the
        # anchor fix made detectable in the first place.
        fleet["healthy.0"] = RESUME_DIALOG_AT_92
        real_detect = prompt_router.detect_prompt

        def detect(visible):
            if visible == RESUME_DIALOG:
                raise ValueError("substring not found")
            return real_detect(visible)

        monkeypatch.setattr(prompt_router, "detect_prompt", detect)
        monkeypatch.setattr(prompt_router, "resolve_parent", lambda *a, **k: ("orch", 0))
        monkeypatch.setattr(prompt_router, "safe_deliver", lambda *a: (True, "delivered"))

        result = prompt_router.sweep()

        # The pane AFTER the crashing one still got routed.
        assert [r["session"] for r in result["routed"]] == ["healthy"]

    def test_a_crash_is_reported_not_swallowed(self, fleet, monkeypatch):
        """Containment must not become silence.

        `except Exception: continue` would turn "the detector crashed" into
        "this pane has no prompt" — indistinguishable from healthy, and
        permanent. That is #885's failure shape with different spelling.
        """
        def boom(visible):
            raise ValueError("substring not found")

        monkeypatch.setattr(prompt_router, "detect_prompt", boom)

        result = prompt_router.sweep()

        failed = {(f["session"], f["pane"]) for f in result["failed"]}
        assert ("blocked", 1) in failed
        assert all("ValueError" in f["error"] for f in result["failed"])

        events = [json.loads(ln) for ln in
                  prompt_router.EVENTS_FILE.read_text().strip().splitlines()]
        failures = [e for e in events if e["event"] == "detect_failed"]
        assert ("blocked", 1) in {(e["session"], e["pane"]) for e in failures}
        assert all("ValueError" in e["error"] for e in failures)

    def test_the_watchdog_prints_a_detector_failure(self, monkeypatch, capsys):
        """It has to reach `agentwire limits tick`, not just a file."""
        import argparse

        from agentwire import limits_cli

        monkeypatch.setattr(limits_cli.usage_limit, "tick", lambda: {
            "skipped": None, "parked": [], "resumed": [], "waiting": []})
        monkeypatch.setattr(prompt_router, "tick", lambda: {
            "routed": [], "deferred": [],
            "failed": [{"session": "blocked", "pane": 1,
                        "error": "ValueError: substring not found"}]})
        for mod in ("inbox", "session_context"):
            monkeypatch.setattr(f"agentwire.{mod}.tick",
                                lambda: {"flushed": [], "deferred": [], "acted": []})
        monkeypatch.setattr("agentwire.scheduler.zombie.tick", lambda: {"killed": []})
        monkeypatch.setattr("agentwire.cohort.tick", lambda: {"reaped": [], "swept": []})

        limits_cli.cmd_limits_tick(argparse.Namespace(json=False))
        out = capsys.readouterr().out
        assert "prompt detector FAILED on blocked.1" in out
        assert "ValueError" in out

    def test_the_marker_gc_still_runs_after_a_crash(self, fleet, monkeypatch):
        """The GC sits after the loop — an unguarded raise skipped it too."""
        prompt_router.write_marker(
            "long-gone", 0, kind="resume", hash="x", status="delivered",
            detected_at=(prompt_router._now() - timedelta(hours=2)).isoformat())

        def boom(visible):
            raise ValueError("substring not found")

        monkeypatch.setattr(prompt_router, "detect_prompt", boom)
        prompt_router.sweep()

        assert prompt_router.read_marker("long-gone", 0) is None

    def test_a_shell_pane_showing_the_text_is_ignored(self, fleet, monkeypatch):
        monkeypatch.setattr(prompt_router, "resolve_parent", lambda *a, **k: ("orch", 0))
        monkeypatch.setattr(prompt_router, "safe_deliver", lambda *a: (True, "delivered"))
        touched = {r["session"] for r in prompt_router.sweep()["routed"]}
        assert "a-shell" not in touched


class TestBlockedPanes:
    def test_it_finds_the_pane_every_liveness_check_calls_healthy(self, fleet):
        """`pane_current_command` is `node` for this pane — alive by every
        existing measure, and doing nothing."""
        blocked = prompt_router.blocked_panes()
        assert [(b["session"], b["pane"], b["kind"]) for b in blocked] == [
            ("blocked", 1, "resume")]

    def test_no_marker_means_nobody_was_told(self, fleet):
        b = prompt_router.blocked_panes()[0]
        assert b["status"] == "unrouted"
        assert b["stuck"] is True

    def test_a_freshly_routed_prompt_is_not_stuck(self, fleet):
        info = detect_prompt(RESUME_DIALOG)
        prompt_router.write_marker(
            "blocked", 1, kind="resume", hash=info.content_hash(),
            parent="orch", status="delivered",
            detected_at=prompt_router._now().isoformat(),
            notified_at=prompt_router._now().isoformat())
        b = prompt_router.blocked_panes()[0]
        assert (b["status"], b["stuck"]) == ("waiting", False)

    def test_a_long_wait_is_stuck(self, fleet):
        old = (prompt_router._now() - timedelta(hours=4)).isoformat()
        prompt_router.write_marker(
            "blocked", 1, kind="resume", hash="x", parent="orch",
            status="delivered", detected_at=old, notified_at=old)
        b = prompt_router.blocked_panes()[0]
        assert (b["status"], b["stuck"], b["waiting_minutes"]) == ("waiting", True, 240)

    def test_a_root_session_is_reported_as_no_parent(self, fleet):
        prompt_router.write_marker(
            "blocked", 1, kind="resume", hash="x", parent=None,
            status="no_parent",
            detected_at=prompt_router._now().isoformat(), notified_at=None)
        assert prompt_router.blocked_panes()[0]["status"] == "no_parent"

    def test_it_never_writes_a_marker(self, fleet):
        prompt_router.blocked_panes()
        assert list(prompt_router.STATE_DIR.glob("*.json")) == []

    def test_a_detector_crash_is_reported_as_a_finding(self, fleet, monkeypatch):
        """The check has to be able to see its own blind spot."""
        def boom(visible):
            raise ValueError("substring not found")

        monkeypatch.setattr(prompt_router, "detect_prompt", boom)
        b = prompt_router.blocked_panes()[0]
        assert (b["status"], b["stuck"]) == ("detector_error", True)
        assert "ValueError" in b["error"]

    def test_unreachable_tmux_is_none_not_empty(self, monkeypatch):
        """"Couldn't look" must not collapse into "looked, all healthy"."""
        monkeypatch.setattr(
            prompt_router, "_tmux",
            lambda *a, **k: SimpleNamespace(returncode=1, stdout=""))
        assert prompt_router.blocked_panes() is None


class TestDoctorSection:
    def test_it_flags_the_blocked_session(self, fleet, capsys):
        from agentwire import doctor_cli

        found = doctor_cli._render_blocked_prompt_section()
        out = capsys.readouterr().out
        assert found == 1
        assert "blocked on a resume prompt" in out
        assert "blocked pane 1" in out
        assert "agentwire prompts answer" in out

    def test_a_healthy_fleet_reports_nothing(self, monkeypatch, capsys):
        from agentwire import doctor_cli

        monkeypatch.setattr(prompt_router, "blocked_panes", lambda: [])
        assert doctor_cli._render_blocked_prompt_section() == 0
        assert "No session is sitting on an unanswered prompt" in capsys.readouterr().out

    def test_a_routed_prompt_is_shown_but_not_counted(self, fleet, capsys):
        from agentwire import doctor_cli

        now = prompt_router._now().isoformat()
        prompt_router.write_marker(
            "blocked", 1, kind="resume", hash="x", parent="orch",
            status="delivered", detected_at=now, notified_at=now)
        found = doctor_cli._render_blocked_prompt_section()
        assert found == 0
        assert "routed to orch" in capsys.readouterr().out

    def test_a_detector_crash_is_flagged_loudly(self, fleet, monkeypatch, capsys):
        from agentwire import doctor_cli

        def boom(visible):
            raise ValueError("substring not found")

        monkeypatch.setattr(prompt_router, "detect_prompt", boom)
        found = doctor_cli._render_blocked_prompt_section()
        out = capsys.readouterr().out
        assert found >= 1   # every agent pane in the fleet raises here
        assert "detector RAISED" in out
        assert "ValueError" in out
        assert "grep detect_failed" in out

    def test_unreachable_tmux_is_not_an_issue(self, monkeypatch, capsys):
        from agentwire import doctor_cli

        monkeypatch.setattr(prompt_router, "blocked_panes", lambda: None)
        assert doctor_cli._render_blocked_prompt_section() == 0
        assert "tmux not reachable" in capsys.readouterr().out


class TestEvents:
    def test_the_escalation_is_logged(self, monkeypatch, sent_emails):
        monkeypatch.setattr(prompt_router, "resolve_parent", lambda *a, **k: None)
        prompt_router.route_prompt("root", 0, detect_prompt(RESUME_DIALOG))
        events = [json.loads(ln) for ln in
                  prompt_router.EVENTS_FILE.read_text().strip().splitlines()]
        assert {"no_parent_escalated", "no_parent"} <= {e["event"] for e in events}
